"""Middle section: turns 401-765"""

SCENARIO_MIDDLE = [
    # === PHASE 18: Pregnancy + Inca Trail cancel (Turns 401-450) ===
    {"turn": 401, "message": "Big news — Tom and I are expecting a baby! Due in August.", "checkpoint": False, "notes": "MAJOR: pregnancy"},
    {"turn": 402, "message": "SA trip in March: I'll be ~5 months pregnant. Doctor says Inca Trail trek too risky.", "checkpoint": False, "notes": "Trek impact"},
    {"turn": 403, "message": "Cancel Inca Trail. We'll visit Machu Picchu by train instead.", "checkpoint": False, "notes": "CANCEL: Inca Trail"},
    {"turn": 404, "message": "PeruRail Vistadome Cusco to Aguas Calientes, $75/person round trip.", "checkpoint": False, "notes": "Replacement"},
    {"turn": 405, "message": "How are we getting to Machu Picchu now?", "checkpoint": True,
     "expected": {"must_contain": ["train|PeruRail"], "must_not_contain": ["trek|Inca Trail|Alpaca|hiking"], "description": "Train, no trek"}},
    {"turn": 406, "message": "Asia in October fine — first trimester, doctor cleared it.", "checkpoint": False, "notes": "Asia OK"},
    {"turn": 407, "message": "Skip snorkeling Koh Samui to be safe. Cancel my spot.", "checkpoint": False, "notes": "Sarah skips snorkeling"},
    {"turn": 408, "message": "Tom, Mike, Lily still snorkel. Not me.", "checkpoint": False, "notes": "3 people snorkeling"},
    {"turn": 409, "message": "Concerns about traveling pregnant in Asia?", "checkpoint": False, "notes": "General"},
    {"turn": 410, "message": "Will talk to doctor.", "checkpoint": False, "notes": "General"},
    {"turn": 411, "message": "Tom excited about being a dad AND traveling.", "checkpoint": False, "notes": "Chatter"},
    {"turn": 412, "message": "Extra bathroom breaks needed. Pregnancy + buses don't mix.", "checkpoint": False, "notes": "Practical"},
    {"turn": 413, "message": "Which Asia activities too strenuous for pregnant woman?", "checkpoint": False, "notes": "Review"},
    {"turn": 414, "message": "Cooking class and tea ceremony fine. Elephant sanctuary OK — no riding.", "checkpoint": False, "notes": "Assessment"},
    {"turn": 415, "message": "It's ethical — feeding and bathing only.", "checkpoint": False, "notes": "Clarification"},
    {"turn": 416, "message": "Ramen tour walking Shinjuku should be OK.", "checkpoint": False, "notes": "Check"},
    {"turn": 417, "message": "Bangkok food tour — will ask about sitting options.", "checkpoint": False, "notes": "General"},
    {"turn": 418, "message": "What email on file for me?", "checkpoint": True,
     "expected": {"must_contain": ["sarahj.travels@gmail.com"], "must_not_contain": [], "description": "Email from turn 120"}},
    {"turn": 419, "message": "Correct!", "checkpoint": False, "notes": "Confirmed"},
    {"turn": 420, "message": "SA hotels should know I'm pregnant.", "checkpoint": False, "notes": "General"},
    {"turn": 421, "message": "Tom watching BA YouTube videos. Excited about steak.", "checkpoint": False, "notes": "Chatter"},
    {"turn": 422, "message": "Found vegan restaurants in BA. Sarkis looks good.", "checkpoint": False, "notes": "Research"},
    {"turn": 423, "message": "Prenatal-friendly activities in Lima?", "checkpoint": False, "notes": "General"},
    {"turn": 424, "message": "Gentle walking tour of historic center.", "checkpoint": False, "notes": "General"},
    {"turn": 425, "message": "Lima city walking tour March 5 afternoon, $20/person.", "checkpoint": False, "notes": "Activity"},
    {"turn": 426, "message": "Larco Museum March 6 morning, $10/person.", "checkpoint": False, "notes": "Activity"},
    {"turn": 427, "message": "Three Lima activities: food tour + walking tour + museum.", "checkpoint": False, "notes": "Count"},
    {"turn": 428, "message": "Buenos Aires activities?", "checkpoint": True,
     "expected": {"must_contain": ["tango|Rojo Tango", "street art|La Boca", "wine"], "must_not_contain": [], "description": "BA activities"}},
    {"turn": 429, "message": "Wine tasting just Tom — I don't drink.", "checkpoint": False, "notes": "No alcohol"},
    {"turn": 430, "message": "Recoleta Cemetery for me while Tom does wine. Free admission.", "checkpoint": False, "notes": "Activity"},
    {"turn": 431, "message": "Wine tasting March 12. Tango March 13. Street art March 11.", "checkpoint": False, "notes": "Scheduling"},
    {"turn": 432, "message": "BA day-by-day?", "checkpoint": True,
     "expected": {"must_contain": ["March 11", "street art|La Boca", "March 12", "wine", "March 13", "tango"], "must_not_contain": [], "description": "BA schedule"}},
    {"turn": 433, "message": "Getting excited!", "checkpoint": False, "notes": "General"},
    {"turn": 434, "message": "Chiang Mai hotel?", "checkpoint": True,
     "expected": {"must_contain": ["Rachamankha"], "must_not_contain": [], "description": "CM hotel"}},
    {"turn": 435, "message": "Koh Samui hotel?", "checkpoint": True,
     "expected": {"must_contain": ["Coco Palm"], "must_not_contain": ["Anantara"], "description": "KS hotel"}},
    {"turn": 436, "message": "Mike's dietary restriction?", "checkpoint": True,
     "expected": {"must_contain": ["shellfish|pescatarian"], "must_not_contain": [], "description": "Mike dietary"}},
    {"turn": 437, "message": "Snorkeling: Tom, Mike, Lily. I'm skipping (pregnancy).", "checkpoint": True,
     "expected": {"must_contain": ["Tom", "Mike", "Lily"], "must_not_contain": ["Sarah", "Patricia"], "description": "Snorkeling: T+M+L"}},
    {"turn": 438, "message": "Four dietary restrictions: vegan, nut, shellfish, lactose. Plus pregnancy.", "checkpoint": False, "notes": "Summary"},
    {"turn": 439, "message": "Every person across ALL travels, dietary/health, which trips.", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "vegan", "pregnant", "Tom", "nut", "Mike", "shellfish", "Lily", "lactose"],
                  "must_not_contain": ["Patricia", "Emily", "vegetarian"], "description": "ALL travelers at turn 439"}},
    {"turn": 440, "message": "Tom wants private sushi dinner Tokyo last night, $200 for two.", "checkpoint": False, "notes": "Activity"},
    {"turn": 441, "message": "Vegan omakase confirmed alongside regular. Book it!", "checkpoint": False, "notes": "Confirmed"},
    {"turn": 442, "message": "What's our last night in Tokyo?", "checkpoint": True,
     "expected": {"must_contain": ["October 10"], "must_not_contain": [], "description": "Last Tokyo night"}},
    {"turn": 443, "message": "Mike's company sending him Singapore mid-October. Might cancel Thailand.", "checkpoint": False, "notes": "Mike uncertain"},
    {"turn": 444, "message": "Mike confirmed cancelled. Lily skipping too.", "checkpoint": False, "notes": "MIKE+LILY CANCELLED"},
    {"turn": 445, "message": "Who's going to Asia now?", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "Tom"], "must_not_contain": ["Mike", "Lily", "Patricia"], "description": "Asia: just S+T"}},
    {"turn": 446, "message": "Snorkeling now just Tom. I'm skipping (pregnancy).", "checkpoint": False, "notes": "1 person"},
    {"turn": 447, "message": "All Bangkok/CM/KS activities: 2 people each.", "checkpoint": False, "notes": "Reduced"},
    {"turn": 448, "message": "Mama Noi's: how many?", "checkpoint": True,
     "expected": {"must_contain": ["2|two|Sarah|Tom"], "must_not_contain": ["Mike", "Lily", "3|three"], "description": "Mama Noi: S+T"}},
    {"turn": 449, "message": "Tom wants to extend Koh Samui: 5 to 7 nights.", "checkpoint": False, "notes": "CHANGE: KS 5→7 nights"},
    {"turn": 450, "message": "Return: Qatar BKK→JFK Oct 25 instead of 23, $900 each.", "checkpoint": False, "notes": "Return changed"},

    # === PHASE 19: Post-cancellation updates (451-500) ===
    {"turn": 451, "message": "New return date?", "checkpoint": True,
     "expected": {"must_contain": ["October 25"], "must_not_contain": ["October 22", "October 23"], "description": "Return Oct 25"}},
    {"turn": 452, "message": "How many nights Koh Samui?", "checkpoint": True,
     "expected": {"must_contain": ["7|seven"], "must_not_contain": ["5|five"], "description": "KS 7 nights"}},
    {"turn": 453, "message": "7 nights tropical island while pregnant. Perfect!", "checkpoint": False, "notes": "General"},
    {"turn": 454, "message": "Tom flight anxiety getting worse. Might get meds.", "checkpoint": False, "notes": "Tom health"},
    {"turn": 455, "message": "Need prenatal clearance docs.", "checkpoint": False, "notes": "Pregnancy prep"},
    {"turn": 456, "message": "Bangkok: how many days?", "checkpoint": True,
     "expected": {"must_contain": ["3|three"], "must_not_contain": [], "description": "Bangkok 3 days"}},
    {"turn": 457, "message": "Elephant Nature Park name correct?", "checkpoint": True,
     "expected": {"must_contain": ["Elephant Nature Park"], "must_not_contain": [], "description": "ENP recall"}},
    {"turn": 458, "message": "Cooking school name?", "checkpoint": True,
     "expected": {"must_contain": ["Mama Noi"], "must_not_contain": [], "description": "Mama Noi recall"}},
    {"turn": 459, "message": "How many trips total?", "checkpoint": True,
     "expected": {"must_contain": ["3|three"], "must_not_contain": [], "description": "3 trips"}},
    {"turn": 460, "message": "Tom's dietary concern?", "checkpoint": True,
     "expected": {"must_contain": ["nut|peanut"], "must_not_contain": [], "description": "Tom nut allergy"}},
    {"turn": 461, "message": "Mine?", "checkpoint": True,
     "expected": {"must_contain": ["vegan"], "must_not_contain": ["vegetarian"], "description": "Sarah vegan"}},
    {"turn": 462, "message": "Cheapest trip?", "checkpoint": True,
     "expected": {"must_contain": ["South America|Peru|Argentina|8,000|8000"], "must_not_contain": [], "description": "SA $8K cheapest"}},
    {"turn": 463, "message": "All Asia hotels?", "checkpoint": True,
     "expected": {"must_contain": ["Sawanoya", "Hyatt", "Chatrium", "Rachamankha", "Coco Palm"],
                  "must_not_contain": ["Park Hotel", "Anantara"], "description": "All Asia hotels"}},
    {"turn": 464, "message": "SA hotels?", "checkpoint": True,
     "expected": {"must_contain": ["Belmond", "Palacio", "Mine Hotel"], "must_not_contain": ["Alvear"], "description": "SA hotels"}},
    {"turn": 465, "message": "Europe Paris hotel?", "checkpoint": True,
     "expected": {"must_contain": ["Hotel Monge"], "must_not_contain": ["Le Petit Moulin"], "description": "Europe hotel"}},
    {"turn": 466, "message": "Miss Paris. Will go back with baby.", "checkpoint": False, "notes": "General"},
    {"turn": 467, "message": "Travel insurance for Asia?", "checkpoint": True,
     "expected": {"must_contain": ["World Nomads|insurance"], "must_not_contain": [], "description": "Asia insurance"}},
    {"turn": 468, "message": "For SA?", "checkpoint": True,
     "expected": {"must_contain": ["World Nomads|insurance"], "must_not_contain": [], "description": "SA insurance"}},
    {"turn": 469, "message": "Baby-proofing house... not travel related!", "checkpoint": False, "notes": "Off-topic"},
    {"turn": 470, "message": "After baby, no traveling for a while. Cramming trips now!", "checkpoint": False, "notes": "General"},
    {"turn": 471, "message": "What does Tom like when traveling?", "checkpoint": False, "notes": "General"},
    {"turn": 472, "message": "Food, languages, working out, craft beer.", "checkpoint": False, "notes": "Tom interests"},
    {"turn": 473, "message": "He's learning Japanese right?", "checkpoint": False, "notes": "Ref"},
    {"turn": 474, "message": "Three months of classes.", "checkpoint": False, "notes": "Confirmed"},
    {"turn": 475, "message": "So exciting!", "checkpoint": False, "notes": "General"},
    {"turn": 476, "message": "What's our accommodation preference?", "checkpoint": True,
     "expected": {"must_contain": ["boutique"], "must_not_contain": [], "description": "Preference: boutique"}},
    {"turn": 477, "message": "Always boutique!", "checkpoint": False, "notes": "General"},
    {"turn": 478, "message": "Tamarind Springs spa KS Oct 20, prenatal massage $90 each. Book it!", "checkpoint": False, "notes": "Activity"},
    {"turn": 479, "message": "Tom surf lessons KS Oct 21, $50.", "checkpoint": False, "notes": "Activity"},
    {"turn": 480, "message": "I'll relax on beach while he surfs.", "checkpoint": False, "notes": "General"},
    {"turn": 481, "message": "How many nights each Thailand location?", "checkpoint": True,
     "expected": {"must_contain": ["Bangkok", "3|three", "Chiang Mai", "4|four", "Koh Samui", "7|seven"],
                  "must_not_contain": ["5|five"], "description": "Thailand nights"}},
    {"turn": 482, "message": "Lots of beach time for pregnant me.", "checkpoint": False, "notes": "General"},
    {"turn": 483, "message": "Travel journal idea. Document everything.", "checkpoint": False, "notes": "General"},
    {"turn": 484, "message": "First hotel we ever booked?", "checkpoint": True,
     "expected": {"must_contain": ["Hotel Monge|boutique"], "must_not_contain": [], "description": "First hotel: Europe"}},
    {"turn": 485, "message": "Most expensive per night?", "checkpoint": False, "notes": "Comparison Q"},
    {"turn": 486, "message": "Hyatt at $300/night.", "checkpoint": False, "notes": "General"},
    {"turn": 487, "message": "Good hotel though.", "checkpoint": False, "notes": "General"},
    {"turn": 488, "message": "Tom bringing snacks for flights. Vegan for me, nut-free for him.", "checkpoint": False, "notes": "Dietary ref"},
    {"turn": 489, "message": "What airline to Tokyo?", "checkpoint": True,
     "expected": {"must_contain": ["ANA"], "must_not_contain": [], "description": "ANA to Tokyo"}},
    {"turn": 490, "message": "Bangkok to JFK?", "checkpoint": True,
     "expected": {"must_contain": ["Qatar"], "must_not_contain": [], "description": "Qatar return"}},
    {"turn": 491, "message": "SA outbound?", "checkpoint": True,
     "expected": {"must_contain": ["LATAM"], "must_not_contain": [], "description": "LATAM to Lima"}},
    {"turn": 492, "message": "SA return?", "checkpoint": True,
     "expected": {"must_contain": ["American"], "must_not_contain": [], "description": "American from BA"}},
    {"turn": 493, "message": "A lot of different airlines!", "checkpoint": False, "notes": "General"},
    {"turn": 494, "message": "Cooking class cost in Chiang Mai?", "checkpoint": True,
     "expected": {"must_contain": ["40"], "must_not_contain": [], "description": "Mama Noi $40/pp"}},
    {"turn": 495, "message": "Elephant sanctuary?", "checkpoint": True,
     "expected": {"must_contain": ["80"], "must_not_contain": [], "description": "ENP $80/pp"}},
    {"turn": 496, "message": "Ramen tour Tokyo?", "checkpoint": True,
     "expected": {"must_contain": ["70"], "must_not_contain": [], "description": "Ramen $70/pp"}},
    {"turn": 497, "message": "Tango show BA?", "checkpoint": True,
     "expected": {"must_contain": ["120"], "must_not_contain": [], "description": "Rojo Tango $120/pp"}},
    {"turn": 498, "message": "Ramen tour date?", "checkpoint": True,
     "expected": {"must_contain": ["October 10"], "must_not_contain": ["October 4", "October 9"], "description": "Ramen Oct 10"}},
    {"turn": 499, "message": "Tom expense tracking. Appreciate help.", "checkpoint": False, "notes": "General"},
    {"turn": 500, "message": "HALF-WAY MEGA CHECKPOINT: Everything. All trips, companions, dietary/health, hotels, activities, budgets.", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "vegan", "pregnant", "Tom", "nut",
                                    "Europe", "June", "Hotel Monge",
                                    "Asia", "October", "Sawanoya", "Hyatt", "Chatrium", "Rachamankha", "Coco Palm", "12,500|12500",
                                    "South America", "March", "Belmond", "Palacio", "Mine Hotel", "8,000|8000"],
                  "must_not_contain": ["Patricia", "Emily", "Mike", "Lily", "vegetarian", "Park Hotel", "Anantara", "Alvear", "15,000|15000", "10,000|10000"],
                  "description": "HALF-WAY MEGA CHECKPOINT turn 500"}},

    # === PHASE 20: Turns 501-600 ===
    {"turn": 501, "message": "Thought about upgrading Sawanoya. Hoshinoya Tokyo $400/night.", "checkpoint": False, "notes": "Potential"},
    {"turn": 502, "message": "No, keep Sawanoya. Save for baby.", "checkpoint": False, "notes": "No change"},
    {"turn": 503, "message": "What Kyoto dates?", "checkpoint": True,
     "expected": {"must_contain": ["October 7"], "must_not_contain": ["October 4"], "description": "Kyoto starts Oct 7"}},
    {"turn": 504, "message": "Then back Tokyo, then Bangkok.", "checkpoint": False, "notes": "General"},
    {"turn": 505, "message": "All Asia activities current?", "checkpoint": True,
     "expected": {"must_contain": ["ramen", "tea ceremony", "cooking|Mama Noi", "elephant", "snorkeling"],
                  "must_not_contain": ["Fuji", "yoga", "scuba", "sushi class"], "description": "Current Asia activities"}},
    {"turn": 506, "message": "What about SA activities?", "checkpoint": True,
     "expected": {"must_contain": ["tango|Rojo", "street art|La Boca", "wine", "food tour|Lima", "PeruRail|train|Machu Picchu"],
                  "must_not_contain": ["Inca Trail|trek|Alpaca"], "description": "Current SA activities"}},
    {"turn": 507, "message": "We've planned a LOT.", "checkpoint": False, "notes": "General"},
    {"turn": 508, "message": "My email?", "checkpoint": True,
     "expected": {"must_contain": ["sarahj.travels@gmail.com"], "must_not_contain": [], "description": "Email recall"}},
    {"turn": 509, "message": "What's the weather in Kyoto October?", "checkpoint": False, "notes": "General"},
    {"turn": 510, "message": "Fall foliage! Beautiful.", "checkpoint": False, "notes": "General"},
    {"turn": 511, "message": "Tom's nut allergy — epi-pen level right?", "checkpoint": True,
     "expected": {"must_contain": ["nut|peanut|epi"], "must_not_contain": [], "description": "Tom nut allergy"}},
    {"turn": 512, "message": "Multiple epi-pens for all trips.", "checkpoint": False, "notes": "Medical"},
    {"turn": 513, "message": "I'm learning konnichiwa and arigatou.", "checkpoint": False, "notes": "General"},
    {"turn": 514, "message": "Tom's learning full sentences.", "checkpoint": False, "notes": "General"},
    {"turn": 515, "message": "BUDGET RAPID FIRE: Europe?", "checkpoint": True,
     "expected": {"must_contain": ["12,000|12000"], "must_not_contain": [], "description": "Europe $12K"}},
    {"turn": 516, "message": "Asia?", "checkpoint": True,
     "expected": {"must_contain": ["12,500|12500"], "must_not_contain": [], "description": "Asia $12.5K"}},
    {"turn": 517, "message": "South America?", "checkpoint": True,
     "expected": {"must_contain": ["8,000|8000"], "must_not_contain": [], "description": "SA $8K"}},
    {"turn": 518, "message": "Three correct!", "checkpoint": False, "notes": "Confirmed"},
    {"turn": 519, "message": "Craving Japanese food. Can't wait.", "checkpoint": False, "notes": "General"},
    {"turn": 520, "message": "Tom making ramen at home. Good miso one.", "checkpoint": False, "notes": "General"},
    {"turn": 521, "message": "Mine has to be vegan of course.", "checkpoint": False, "notes": "Vegan ref"},
    {"turn": 522, "message": "Best miso ramen in Tokyo on the ramen tour?", "checkpoint": False, "notes": "General"},
    {"turn": 523, "message": "What date ramen tour?", "checkpoint": True,
     "expected": {"must_contain": ["October 10"], "must_not_contain": ["October 4"], "description": "Ramen tour Oct 10"}},
    {"turn": 524, "message": "Last full Tokyo day. Sushi dinner that evening too.", "checkpoint": False, "notes": "Activity ref"},
    {"turn": 525, "message": "What airline Tokyo→Bangkok?", "checkpoint": True,
     "expected": {"must_contain": ["Thai Airways"], "must_not_contain": [], "description": "Thai Airways"}},
    {"turn": 526, "message": "BKK→Chiang Mai?", "checkpoint": True,
     "expected": {"must_contain": ["AirAsia"], "must_not_contain": [], "description": "AirAsia"}},
    {"turn": 527, "message": "Chiang Mai→Koh Samui?", "checkpoint": True,
     "expected": {"must_contain": ["Bangkok Airways"], "must_not_contain": [], "description": "Bangkok Airways"}},
    {"turn": 528, "message": "Lots of airlines!", "checkpoint": False, "notes": "General"},
    {"turn": 529, "message": "RAPID FIRE HOTELS: Tokyo?", "checkpoint": True,
     "expected": {"must_contain": ["Sawanoya"], "must_not_contain": ["Park Hotel"], "description": "Sawanoya"}},
    {"turn": 530, "message": "Kyoto?", "checkpoint": True,
     "expected": {"must_contain": ["Hyatt"], "must_not_contain": [], "description": "Hyatt"}},
    {"turn": 531, "message": "Bangkok?", "checkpoint": True,
     "expected": {"must_contain": ["Chatrium"], "must_not_contain": [], "description": "Chatrium"}},
    {"turn": 532, "message": "Chiang Mai?", "checkpoint": True,
     "expected": {"must_contain": ["Rachamankha"], "must_not_contain": [], "description": "Rachamankha"}},
    {"turn": 533, "message": "Koh Samui?", "checkpoint": True,
     "expected": {"must_contain": ["Coco Palm"], "must_not_contain": ["Anantara"], "description": "Coco Palm"}},
    {"turn": 534, "message": "Lima?", "checkpoint": True,
     "expected": {"must_contain": ["Belmond"], "must_not_contain": [], "description": "Belmond"}},
    {"turn": 535, "message": "Cusco?", "checkpoint": True,
     "expected": {"must_contain": ["Palacio"], "must_not_contain": [], "description": "Palacio"}},
    {"turn": 536, "message": "Buenos Aires?", "checkpoint": True,
     "expected": {"must_contain": ["Mine Hotel"], "must_not_contain": ["Alvear"], "description": "Mine Hotel"}},
    {"turn": 537, "message": "8 for 8! Amazing.", "checkpoint": False, "notes": "General"},
    {"turn": 538, "message": "Tom's excited about elephant sanctuary.", "checkpoint": False, "notes": "General"},
    {"turn": 539, "message": "What sanctuary name?", "checkpoint": True,
     "expected": {"must_contain": ["Elephant Nature Park"], "must_not_contain": [], "description": "ENP"}},
    {"turn": 540, "message": "What date?", "checkpoint": True,
     "expected": {"must_contain": ["October 16"], "must_not_contain": ["October 15"], "description": "ENP Oct 16"}},
    {"turn": 541, "message": "Cooking class date?", "checkpoint": True,
     "expected": {"must_contain": ["October 15", "Mama Noi"], "must_not_contain": [], "description": "Mama Noi Oct 15"}},
    {"turn": 542, "message": "Two big CM days.", "checkpoint": False, "notes": "General"},
    {"turn": 543, "message": "Then Koh Samui paradise.", "checkpoint": False, "notes": "General"},
    {"turn": 544, "message": "I love how much planning we've done.", "checkpoint": False, "notes": "General"},
    {"turn": 545, "message": "Three trips in one year!", "checkpoint": False, "notes": "General"},
    {"turn": 546, "message": "Peru month?", "checkpoint": True,
     "expected": {"must_contain": ["March"], "must_not_contain": [], "description": "Peru: March"}},
    {"turn": 547, "message": "Japan month?", "checkpoint": True,
     "expected": {"must_contain": ["October"], "must_not_contain": [], "description": "Japan: October"}},
    {"turn": 548, "message": "Europe was June.", "checkpoint": False, "notes": "General"},
    {"turn": 549, "message": "Nice spread through the year.", "checkpoint": False, "notes": "General"},
    {"turn": 550, "message": "STATUS CHECK: Who's on each trip?", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "Tom"], "must_not_contain": ["Patricia", "Mike", "Lily", "Emily"],
                  "description": "All trips just S+T now"}},

    # Turns 551-600: More filler
    {"turn": 551, "message": "SA and Asia trips are different months, good for packing.", "checkpoint": False, "notes": "General"},
    {"turn": 552, "message": "Tom's making expense spreadsheet.", "checkpoint": False, "notes": "General"},
    {"turn": 553, "message": "BA hotel name?", "checkpoint": True,
     "expected": {"must_contain": ["Mine Hotel"], "must_not_contain": ["Alvear"], "description": "Mine Hotel"}},
    {"turn": 554, "message": "Price per night?", "checkpoint": True,
     "expected": {"must_contain": ["120"], "must_not_contain": ["250"], "description": "$120/night"}},
    {"turn": 555, "message": "Boutique style right? Love that.", "checkpoint": False, "notes": "Preference ref"},
    {"turn": 556, "message": "Tom worried about getting sick in Asia. First aid kit?", "checkpoint": False, "notes": "General"},
    {"turn": 557, "message": "Good idea.", "checkpoint": False, "notes": "General"},
    {"turn": 558, "message": "When is SA trip?", "checkpoint": True,
     "expected": {"must_contain": ["March 5|March 15|March"], "must_not_contain": [], "description": "SA March"}},
    {"turn": 559, "message": "I'll be about 20 weeks pregnant. Doctor says fine to fly.", "checkpoint": False, "notes": "Medical"},
    {"turn": 560, "message": "Lima hotel?", "checkpoint": True,
     "expected": {"must_contain": ["Belmond"], "must_not_contain": [], "description": "Lima: Belmond"}},
    {"turn": 561, "message": "Cusco?", "checkpoint": True,
     "expected": {"must_contain": ["Palacio"], "must_not_contain": [], "description": "Cusco: Palacio"}},
    {"turn": 562, "message": "Train to Machu Picchu called?", "checkpoint": True,
     "expected": {"must_contain": ["PeruRail|Vistadome"], "must_not_contain": ["Alpaca|Inca Trail"], "description": "PeruRail"}},
    {"turn": 563, "message": "Better than trekking at 5 months pregnant!", "checkpoint": False, "notes": "General"},
    {"turn": 564, "message": "Europe budget?", "checkpoint": True,
     "expected": {"must_contain": ["12,000|12000"], "must_not_contain": ["8,000|8000"], "description": "Europe $12K"}},
    {"turn": 565, "message": "Asia?", "checkpoint": True,
     "expected": {"must_contain": ["12,500|12500"], "must_not_contain": ["15,000|15000"], "description": "Asia $12.5K"}},
    {"turn": 566, "message": "SA?", "checkpoint": True,
     "expected": {"must_contain": ["8,000|8000"], "must_not_contain": ["10,000|10000"], "description": "SA $8K"}},
    {"turn": 567, "message": "Total: $32.5K on travel!", "checkpoint": False, "notes": "Math"},
    {"turn": 568, "message": "Patricia sends her love. Feeling better.", "checkpoint": False, "notes": "Patricia ref (not traveler)"},
    {"turn": 569, "message": "Don't forget kimono gift from Japan for her. $200 budgeted.", "checkpoint": False, "notes": "Gift"},
    {"turn": 570, "message": "Vegan food in Japan — shojin ryori!", "checkpoint": False, "notes": "General"},
    {"turn": 571, "message": "Thai vegan food is amazing too.", "checkpoint": False, "notes": "General"},
    {"turn": 572, "message": "Tom wants pad thai, no nuts.", "checkpoint": False, "notes": "Dietary ref"},
    {"turn": 573, "message": "All booked Asia activities?", "checkpoint": True,
     "expected": {"must_contain": ["ramen", "tea ceremony", "cooking|Mama Noi", "elephant", "snorkeling", "sushi dinner", "spa|Tamarind", "surf"],
                  "must_not_contain": ["Fuji", "yoga", "scuba", "sushi class"], "description": "All Asia activities"}},
    {"turn": 574, "message": "SA activities?", "checkpoint": True,
     "expected": {"must_contain": ["tango|Rojo", "street art|La Boca", "wine", "food tour|Lima", "walking tour", "museum|Larco", "train|PeruRail"],
                  "must_not_contain": ["Inca Trail|trek"], "description": "All SA activities"}},
    {"turn": 575, "message": "We've planned a LOT. Impressive.", "checkpoint": False, "notes": "General"},
    {"turn": 576, "message": "Can't wait!", "checkpoint": False, "notes": "General"},

    {"turn": 577, "message": "CHECKPOINT 577: Complete state of all three trips.", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "vegan", "pregnant", "Tom", "nut",
                                    "Europe", "Hotel Monge",
                                    "Asia", "October", "Sawanoya", "Hyatt", "Chatrium", "Rachamankha", "Coco Palm", "12,500|12500",
                                    "South America", "March", "Belmond", "Palacio", "Mine Hotel", "8,000|8000"],
                  "must_not_contain": ["Patricia", "Mike", "Lily", "Emily", "vegetarian", "Park Hotel", "Anantara", "Alvear",
                                       "Fuji", "Inca Trail|trek", "15,000|15000", "10,000|10000"],
                  "description": "CHECKPOINT 577"}},

    # Turns 578-650: Filler with periodic quick checks
    {"turn": 578, "message": "Tom packing already. So typical.", "checkpoint": False, "notes": "General"},
    {"turn": 579, "message": "I should start too.", "checkpoint": False, "notes": "General"},
    {"turn": 580, "message": "Compression socks, prenatal vitamins, comfortable shoes...", "checkpoint": False, "notes": "Packing"},
    {"turn": 581, "message": "Tom: camera, epi-pen, anxiety meds.", "checkpoint": False, "notes": "Packing"},
    {"turn": 582, "message": "Should we rent a car in Koh Samui?", "checkpoint": False, "notes": "General"},
    {"turn": 583, "message": "Hire a driver. Safer.", "checkpoint": False, "notes": "General"},
    {"turn": 584, "message": "Good idea.", "checkpoint": False, "notes": "General"},
    {"turn": 585, "message": "How many total flights across upcoming trips?", "checkpoint": False, "notes": "Count Q"},
    {"turn": 586, "message": "Asia: 5. SA: 4. Nine total!", "checkpoint": False, "notes": "Count"},
    {"turn": 587, "message": "My pregnant body is going to hate me.", "checkpoint": False, "notes": "General"},
    {"turn": 588, "message": "Compression socks and aisle seats!", "checkpoint": False, "notes": "General"},
    {"turn": 589, "message": "Tom making a flight playlist.", "checkpoint": False, "notes": "General"},
    {"turn": 590, "message": "We arrive Tokyo evening Oct 4. First full day Oct 5.", "checkpoint": False, "notes": "General"},
    {"turn": 591, "message": "What's planned Oct 5?", "checkpoint": False, "notes": "Schedule Q"},
    {"turn": 592, "message": "Just exploring! No fixed plans.", "checkpoint": False, "notes": "General"},
    {"turn": 593, "message": "Kyoto starting Oct 7.", "checkpoint": False, "notes": "General"},
    {"turn": 594, "message": "Tea ceremony Oct 8.", "checkpoint": False, "notes": "Activity ref"},
    {"turn": 595, "message": "Tea ceremony cost?", "checkpoint": True,
     "expected": {"must_contain": ["60"], "must_not_contain": [], "description": "Tea $60/pp"}},
    {"turn": 596, "message": "For two now.", "checkpoint": False, "notes": "General"},
    {"turn": 597, "message": "Ramen tour Oct 10, sushi dinner Oct 10 evening.", "checkpoint": False, "notes": "Ref"},
    {"turn": 598, "message": "Bangkok Oct 11. Food tour first day.", "checkpoint": False, "notes": "Ref"},
    {"turn": 599, "message": "Cruise Oct 12.", "checkpoint": False, "notes": "Ref"},
    {"turn": 600, "message": "CHECKPOINT 600: Everything currently accurate.", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "vegan", "pregnant", "Tom", "nut",
                                    "Asia", "October", "Sawanoya", "Hyatt", "Chatrium", "Rachamankha", "Coco Palm", "ANA", "Qatar", "12,500|12500",
                                    "South America", "March", "Belmond", "Palacio", "Mine Hotel", "LATAM", "American", "8,000|8000",
                                    "ramen", "tea ceremony", "elephant", "tango"],
                  "must_not_contain": ["Patricia", "Mike", "Lily", "Emily", "vegetarian", "Park Hotel", "Anantara", "Alvear",
                                       "Fuji", "Inca Trail|trek", "15,000|15000", "10,000|10000"],
                  "description": "CHECKPOINT 600"}},

    # Turns 601-700: Extended filler with occasional recall
    {"turn": 601, "message": "Work schedules cleared for both trips.", "checkpoint": False, "notes": "General"},
    {"turn": 602, "message": "Harajuku shopping in Tokyo.", "checkpoint": False, "notes": "General"},
    {"turn": 603, "message": "Shimokitazawa vintage shops.", "checkpoint": False, "notes": "General"},
    {"turn": 604, "message": "Baby clothes hunting!", "checkpoint": False, "notes": "General"},
    {"turn": 605, "message": "Tom learning Thai greetings too.", "checkpoint": False, "notes": "General"},
    {"turn": 606, "message": "What should we see in Kyoto besides Kinkaku-ji?", "checkpoint": False, "notes": "General"},
    {"turn": 607, "message": "Fushimi Inari! And Arashiyama Bamboo Grove.", "checkpoint": False, "notes": "General"},
    {"turn": 608, "message": "Lots of walking. I'll take it slow — pregnant.", "checkpoint": False, "notes": "General"},
    {"turn": 609, "message": "Tom getting a haircut before the trip.", "checkpoint": False, "notes": "General"},
    {"turn": 610, "message": "Should we buy gifts for Tom's colleagues?", "checkpoint": False, "notes": "General"},
    {"turn": 611, "message": "Japanese snacks or Thai silk. Budget $100.", "checkpoint": False, "notes": "Expense"},
    {"turn": 612, "message": "And alpaca wool from Peru for Patricia.", "checkpoint": False, "notes": "Gift plan"},
    {"turn": 613, "message": "She'll love it.", "checkpoint": False, "notes": "General"},
    {"turn": 614, "message": "What was the very first thing I told you?", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "Europe|trip"], "must_not_contain": [], "description": "First message recall"}},
    {"turn": 615, "message": "Feels like forever ago.", "checkpoint": False, "notes": "General"},
    {"turn": 616, "message": "How many hotel changes for Tokyo?", "checkpoint": False, "notes": "Meta Q"},
    {"turn": 617, "message": "Sawanoya → Park Hotel → Sawanoya. Full circle!", "checkpoint": False, "notes": "History"},
    {"turn": 618, "message": "Tom asked: original Asia budget vs now?", "checkpoint": True,
     "expected": {"must_contain": ["15,000|15000", "12,500|12500"], "must_not_contain": [], "description": "Asia: $15K→$12.5K"}},
    {"turn": 619, "message": "SA budget change?", "checkpoint": True,
     "expected": {"must_contain": ["10,000|10000", "8,000|8000"], "must_not_contain": [], "description": "SA: $10K→$8K"}},
    {"turn": 620, "message": "We're good at adapting!", "checkpoint": False, "notes": "General"},
    {"turn": 621, "message": "Europe cities?", "checkpoint": True,
     "expected": {"must_contain": ["Paris", "Rome", "Florence"], "must_not_contain": ["Barcelona"], "description": "Europe cities"}},
    {"turn": 622, "message": "Asia cities?", "checkpoint": True,
     "expected": {"must_contain": ["Tokyo", "Kyoto", "Bangkok", "Chiang Mai", "Koh Samui"], "must_not_contain": [], "description": "Asia cities"}},
    {"turn": 623, "message": "SA cities?", "checkpoint": True,
     "expected": {"must_contain": ["Lima", "Cusco", "Buenos Aires"], "must_not_contain": ["Mendoza"], "description": "SA cities"}},
    {"turn": 624, "message": "11 cities total!", "checkpoint": False, "notes": "General"},
    {"turn": 625, "message": "So many stories to tell.", "checkpoint": False, "notes": "General"},
    {"turn": 626, "message": "Photo book for each trip.", "checkpoint": False, "notes": "General"},
    {"turn": 627, "message": "And one for the baby.", "checkpoint": False, "notes": "General"},
    {"turn": 628, "message": "The before-baby adventures!", "checkpoint": False, "notes": "General"},
    {"turn": 629, "message": "Tom planning baby's first trip. Costa Rica maybe.", "checkpoint": False, "notes": "General"},
    {"turn": 630, "message": "Next year's problem!", "checkpoint": False, "notes": "General"},
    {"turn": 631, "message": "First upcoming trip?", "checkpoint": True,
     "expected": {"must_contain": ["October", "Asia|Japan"], "must_not_contain": [], "description": "Next: Asia Oct"}},
    {"turn": 632, "message": "About a month away!", "checkpoint": False, "notes": "General"},
    {"turn": 633, "message": "Then SA in March.", "checkpoint": False, "notes": "General"},
    {"turn": 634, "message": "Amazing year.", "checkpoint": False, "notes": "General"},
    {"turn": 635, "message": "What was my original dietary restriction?", "checkpoint": True,
     "expected": {"must_contain": ["vegetarian"], "must_not_contain": [], "description": "Original: vegetarian"}},
    {"turn": 636, "message": "And now?", "checkpoint": True,
     "expected": {"must_contain": ["vegan"], "must_not_contain": ["vegetarian"], "description": "Current: vegan"}},
    {"turn": 637, "message": "Plus no alcohol and pregnant!", "checkpoint": False, "notes": "General"},
    {"turn": 638, "message": "All companions who ever came and went?", "checkpoint": True,
     "expected": {"must_contain": ["Emily", "Patricia", "Mike", "Lily"], "must_not_contain": [],
                  "description": "All companions ever: Emily, Patricia, Mike, Lily"}},
    {"turn": 639, "message": "Four people! All cancelled for different reasons.", "checkpoint": False, "notes": "General"},
    {"turn": 640, "message": "What cancelled activities across ALL trips?", "checkpoint": True,
     "expected": {"must_contain": ["sushi class", "scuba", "yoga|Vikasa", "Nara", "Fuji", "Inca Trail|trek"],
                  "must_not_contain": [], "description": "All cancelled activities"}},
    {"turn": 641, "message": "Lots! But remaining ones are great.", "checkpoint": False, "notes": "General"},
    {"turn": 642, "message": "Tom counting down: 20 days to Asia!", "checkpoint": False, "notes": "General"},
    {"turn": 643, "message": "Exciting!", "checkpoint": False, "notes": "General"},
    {"turn": 644, "message": "I can't sleep.", "checkpoint": False, "notes": "General"},
    {"turn": 645, "message": "Tom watching Japan vlogs late at night.", "checkpoint": False, "notes": "General"},
    {"turn": 646, "message": "We should make a WhatsApp group. Just us two haha.", "checkpoint": False, "notes": "General"},
    {"turn": 647, "message": "Tom's packing list: camera, epi-pen, meds, hiking shoes, laptop.", "checkpoint": False, "notes": "Packing"},
    {"turn": 648, "message": "Mine: prenatal vitamins, compression socks, maternity clothes.", "checkpoint": False, "notes": "Packing"},
    {"turn": 649, "message": "Ready!", "checkpoint": False, "notes": "General"},
    {"turn": 650, "message": "CHECKPOINT 650: All airlines across both upcoming trips.", "checkpoint": True,
     "expected": {"must_contain": ["ANA", "Thai Airways", "AirAsia", "Bangkok Airways", "Qatar", "LATAM", "Aerolineas", "American"],
                  "must_not_contain": ["Delta", "United"], "description": "All airlines"}},

    # Turns 651-765: Final filler before the last stretch
    {"turn": 651, "message": "What hotel Rome on Europe trip?", "checkpoint": True,
     "expected": {"must_contain": ["Campo de' Fiori"], "must_not_contain": [], "description": "Rome: Campo de' Fiori"}},
    {"turn": 652, "message": "The noisy one. Never again.", "checkpoint": False, "notes": "General"},
    {"turn": 653, "message": "Tom's learning from that.", "checkpoint": False, "notes": "General"},
    {"turn": 654, "message": "Best Europe hotel?", "checkpoint": True,
     "expected": {"must_contain": ["Hotel Monge"], "must_not_contain": [], "description": "Best: Hotel Monge"}},
    {"turn": 655, "message": "Definitely.", "checkpoint": False, "notes": "General"},
    {"turn": 656, "message": "What language is Tom learning?", "checkpoint": True,
     "expected": {"must_contain": ["Japanese"], "must_not_contain": [], "description": "Tom: Japanese"}},
    {"turn": 657, "message": "And some Thai too.", "checkpoint": False, "notes": "General"},
    {"turn": 658, "message": "Polyglot in the making.", "checkpoint": False, "notes": "General"},
    {"turn": 659, "message": "I should learn basic greetings too.", "checkpoint": False, "notes": "General"},
    {"turn": 660, "message": "Patricia's temple recommendation for baby luck in Kyoto: Suzumushi-dera.", "checkpoint": False, "notes": "Detail"},
    {"turn": 661, "message": "Sweet of her. We'll visit.", "checkpoint": False, "notes": "General"},
    {"turn": 662, "message": "How many Kyoto days?", "checkpoint": True,
     "expected": {"must_contain": ["3|three|October 7|October 9"], "must_not_contain": [], "description": "Kyoto ~3 days"}},
    {"turn": 663, "message": "Tea ceremony date?", "checkpoint": True,
     "expected": {"must_contain": ["October 8"], "must_not_contain": [], "description": "Tea Oct 8"}},
    {"turn": 664, "message": "I'll wear a kimono for it.", "checkpoint": False, "notes": "General"},
    {"turn": 665, "message": "Tom too — a yukata.", "checkpoint": False, "notes": "General"},
    {"turn": 666, "message": "Amazing.", "checkpoint": False, "notes": "General"},
    {"turn": 667, "message": "No more changes! We promised.", "checkpoint": False, "notes": "General"},
    {"turn": 668, "message": "Famous last words haha.", "checkpoint": False, "notes": "General"},
    {"turn": 669, "message": "Spa in Koh Samui name?", "checkpoint": True,
     "expected": {"must_contain": ["Tamarind"], "must_not_contain": [], "description": "Tamarind Springs"}},
    {"turn": 670, "message": "Spa date?", "checkpoint": True,
     "expected": {"must_contain": ["October 20"], "must_not_contain": [], "description": "Spa Oct 20"}},
    {"turn": 671, "message": "Tom surf date?", "checkpoint": True,
     "expected": {"must_contain": ["October 21"], "must_not_contain": [], "description": "Surf Oct 21"}},
    {"turn": 672, "message": "Perfect Koh Samui schedule.", "checkpoint": False, "notes": "General"},
    {"turn": 673, "message": "I love our plan.", "checkpoint": False, "notes": "General"},
    {"turn": 674, "message": "Tango show name in BA?", "checkpoint": True,
     "expected": {"must_contain": ["Rojo Tango"], "must_not_contain": [], "description": "Rojo Tango"}},
    {"turn": 675, "message": "March 13 last night.", "checkpoint": False, "notes": "General"},
    {"turn": 676, "message": "Need maternity dress for it.", "checkpoint": False, "notes": "General"},
    {"turn": 677, "message": "Street art tour BA?", "checkpoint": True,
     "expected": {"must_contain": ["La Boca"], "must_not_contain": [], "description": "La Boca"}},
    {"turn": 678, "message": "March 11.", "checkpoint": False, "notes": "General"},
    {"turn": 679, "message": "Wine tasting Tom only March 12.", "checkpoint": False, "notes": "General"},
    {"turn": 680, "message": "Accommodation preference?", "checkpoint": True,
     "expected": {"must_contain": ["boutique"], "must_not_contain": [], "description": "Boutique pref"}},
    {"turn": 681, "message": "Always!", "checkpoint": False, "notes": "General"},
    {"turn": 682, "message": "Any last-minute changes?", "checkpoint": False, "notes": "General"},
    {"turn": 683, "message": "Nope! Everything booked.", "checkpoint": False, "notes": "General"},
    {"turn": 684, "message": "Tom's mom sends good wishes.", "checkpoint": False, "notes": "General"},
    {"turn": 685, "message": "She's sweet. The kimono will make her day.", "checkpoint": False, "notes": "General"},
    {"turn": 686, "message": "Weather in KS late October?", "checkpoint": False, "notes": "General"},
    {"turn": 687, "message": "End of rainy season. Should be fine.", "checkpoint": False, "notes": "General"},
    {"turn": 688, "message": "Fingers crossed for snorkeling weather.", "checkpoint": False, "notes": "General"},
    {"turn": 689, "message": "Just Tom snorkeling though.", "checkpoint": False, "notes": "General"},
    {"turn": 690, "message": "I'll cheer from the boat.", "checkpoint": False, "notes": "General"},
    {"turn": 691, "message": "What was Inca Trail replaced by?", "checkpoint": True,
     "expected": {"must_contain": ["train|PeruRail"], "must_not_contain": ["trek"], "description": "PeruRail replaced trek"}},
    {"turn": 692, "message": "Smart change.", "checkpoint": False, "notes": "General"},
    {"turn": 693, "message": "Alpaca Expeditions was the company right?", "checkpoint": True,
     "expected": {"must_contain": ["Alpaca"], "must_not_contain": [], "description": "Cancelled company recall"}},
    {"turn": 694, "message": "We'll use them next time.", "checkpoint": False, "notes": "General"},
    {"turn": 695, "message": "What dietary restrictions for restaurants now? Just us two.", "checkpoint": True,
     "expected": {"must_contain": ["vegan", "nut"], "must_not_contain": ["vegetarian", "shellfish", "lactose"],
                  "description": "Current: vegan + nut only"}},
    {"turn": 696, "message": "Much simpler!", "checkpoint": False, "notes": "General"},
    {"turn": 697, "message": "Remember when we had four restrictions?", "checkpoint": False, "notes": "General"},
    {"turn": 698, "message": "Vegan, nuts, shellfish, lactose. What a combo.", "checkpoint": False, "notes": "General"},
    {"turn": 699, "message": "At least two is manageable.", "checkpoint": False, "notes": "General"},

    {"turn": 700, "message": "CHECKPOINT 700: Everything currently accurate.", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "vegan", "pregnant", "Tom", "nut",
                                    "Asia", "October", "Sawanoya", "Hyatt", "Chatrium", "Rachamankha", "Coco Palm", "12,500|12500",
                                    "South America", "March", "Belmond", "Palacio", "Mine Hotel", "8,000|8000",
                                    "ramen", "tea ceremony", "elephant", "tango", "PeruRail|train"],
                  "must_not_contain": ["Patricia", "Mike", "Lily", "Emily", "vegetarian", "Park Hotel", "Anantara", "Alvear",
                                       "Fuji", "Inca Trail|trek", "15,000|15000", "10,000|10000", "scuba", "yoga"],
                  "description": "CHECKPOINT 700"}},

    # Turns 701-765: More filler
    {"turn": 701, "message": "Less than a month to Asia trip!", "checkpoint": False, "notes": "General"},
    {"turn": 702, "message": "Countdown: 28 days.", "checkpoint": False, "notes": "General"},
    {"turn": 703, "message": "Full Japan+Thailand itinerary one more time?", "checkpoint": True,
     "expected": {"must_contain": ["October 4", "Tokyo", "Kyoto", "October 11", "Bangkok", "Chiang Mai", "Koh Samui", "October 25"],
                  "must_not_contain": ["October 1", "Fuji", "Patricia", "Mike"], "description": "Final Asia itinerary"}},
    {"turn": 704, "message": "Hotels in each city?", "checkpoint": True,
     "expected": {"must_contain": ["Sawanoya", "Hyatt", "Chatrium", "Rachamankha", "Coco Palm"],
                  "must_not_contain": ["Park Hotel", "Anantara"], "description": "All Asia hotels"}},
    {"turn": 705, "message": "Perfect.", "checkpoint": False, "notes": "General"},
    {"turn": 706, "message": "Need to buy yen and baht.", "checkpoint": False, "notes": "General"},
    {"turn": 707, "message": "And soles and pesos for SA.", "checkpoint": False, "notes": "General"},
    {"turn": 708, "message": "Five currencies across all trips!", "checkpoint": False, "notes": "Count"},
    {"turn": 709, "message": "International travel is wild.", "checkpoint": False, "notes": "General"},
    {"turn": 710, "message": "Tom downloaded currency converter.", "checkpoint": False, "notes": "General"},
    {"turn": 711, "message": "Smart.", "checkpoint": False, "notes": "General"},
    {"turn": 712, "message": "Who's Sarah?", "checkpoint": True,
     "expected": {"must_contain": ["Sarah"], "must_not_contain": [], "description": "User identification"}},
    {"turn": 713, "message": "Just checking you still know me haha.", "checkpoint": False, "notes": "Humor"},
    {"turn": 714, "message": "And my husband?", "checkpoint": True,
     "expected": {"must_contain": ["Tom"], "must_not_contain": [], "description": "Husband: Tom"}},
    {"turn": 715, "message": "Baby due?", "checkpoint": True,
     "expected": {"must_contain": ["August"], "must_not_contain": [], "description": "Due: August"}},
    {"turn": 716, "message": "All good!", "checkpoint": False, "notes": "General"},
    {"turn": 717, "message": "How many trips?", "checkpoint": True,
     "expected": {"must_contain": ["3|three"], "must_not_contain": [], "description": "3 trips"}},
    {"turn": 718, "message": "Europe (done), Asia (upcoming), SA (upcoming).", "checkpoint": False, "notes": "General"},
    {"turn": 719, "message": "Can't wait for both!", "checkpoint": False, "notes": "General"},
    {"turn": 720, "message": "Tom's Japanese teacher is impressed by his dedication.", "checkpoint": False, "notes": "General"},
    {"turn": 721, "message": "He practices every day.", "checkpoint": False, "notes": "General"},
    {"turn": 722, "message": "I just learn food words.", "checkpoint": False, "notes": "General"},
    {"turn": 723, "message": "Priorities!", "checkpoint": False, "notes": "General"},
    {"turn": 724, "message": "What was that Kyoto temple Patricia recommended?", "checkpoint": False, "notes": "Detail recall"},
    {"turn": 725, "message": "Suzumushi-dera for baby luck.", "checkpoint": False, "notes": "General"},
    {"turn": 726, "message": "So sweet.", "checkpoint": False, "notes": "General"},
    {"turn": 727, "message": "OK I think we're truly done planning.", "checkpoint": False, "notes": "General"},
    {"turn": 728, "message": "For real this time.", "checkpoint": False, "notes": "General"},
    {"turn": 729, "message": "No more changes.", "checkpoint": False, "notes": "General"},
    {"turn": 730, "message": "Tom swears on his Don Julio steak.", "checkpoint": False, "notes": "Humor"},
    {"turn": 731, "message": "Haha deal.", "checkpoint": False, "notes": "General"},
    {"turn": 732, "message": "The longest flight is JFK→Tokyo at 14 hours.", "checkpoint": False, "notes": "General"},
    {"turn": 733, "message": "Tom's anxiety meds will help.", "checkpoint": False, "notes": "General"},
    {"turn": 734, "message": "And I'll be right next to him.", "checkpoint": False, "notes": "General"},
    {"turn": 735, "message": "We've been through so much planning.", "checkpoint": False, "notes": "General"},
    {"turn": 736, "message": "Three trips, multiple companions, budget changes, life changes.", "checkpoint": False, "notes": "Summary"},
    {"turn": 737, "message": "It's been a journey.", "checkpoint": False, "notes": "General"},
    {"turn": 738, "message": "I appreciate you keeping track of everything.", "checkpoint": False, "notes": "General"},
    {"turn": 739, "message": "Maternity clothes shopping this weekend.", "checkpoint": False, "notes": "General"},
    {"turn": 740, "message": "Comfortable travel wear.", "checkpoint": False, "notes": "General"},
    {"turn": 741, "message": "Tom needs a new suitcase.", "checkpoint": False, "notes": "General"},
    {"turn": 742, "message": "His old one broke on the Europe trip.", "checkpoint": False, "notes": "General"},
    {"turn": 743, "message": "Getting a Rimowa. Fancy!", "checkpoint": False, "notes": "General"},
    {"turn": 744, "message": "He deserves it.", "checkpoint": False, "notes": "General"},
    {"turn": 745, "message": "We deserve all of this. It's going to be incredible.", "checkpoint": False, "notes": "General"},
    {"turn": 746, "message": "From Sarah planning a Europe trip to three-trip veteran with a baby on the way.", "checkpoint": False, "notes": "Reflection"},
    {"turn": 747, "message": "Life moves fast!", "checkpoint": False, "notes": "General"},
    {"turn": 748, "message": "I'm going to cry happy tears on that ANA flight.", "checkpoint": False, "notes": "General"},
    {"turn": 749, "message": "Tom will too. He's a softie.", "checkpoint": False, "notes": "General"},
    {"turn": 750, "message": "CHECKPOINT 750: All 8 hotels across upcoming trips.", "checkpoint": True,
     "expected": {"must_contain": ["Sawanoya", "Hyatt", "Chatrium", "Rachamankha", "Coco Palm", "Belmond", "Palacio", "Mine Hotel"],
                  "must_not_contain": ["Park Hotel", "Anantara", "Alvear"],
                  "description": "CHECKPOINT 750: All 8 hotels"}},
    {"turn": 751, "message": "Love them all.", "checkpoint": False, "notes": "General"},
    {"turn": 752, "message": "All boutique or unique!", "checkpoint": False, "notes": "General"},
    {"turn": 753, "message": "That's our thing.", "checkpoint": False, "notes": "General"},
    {"turn": 754, "message": "OK I need to go to sleep. Early morning tomorrow.", "checkpoint": False, "notes": "General"},
    {"turn": 755, "message": "Pregnancy makes me tired but excited.", "checkpoint": False, "notes": "General"},
    {"turn": 756, "message": "Tom's already asleep. Early riser.", "checkpoint": False, "notes": "General"},
    {"turn": 757, "message": "I'll dream about Koh Samui beaches.", "checkpoint": False, "notes": "General"},
    {"turn": 758, "message": "And Tokyo ramen.", "checkpoint": False, "notes": "General"},
    {"turn": 759, "message": "And Buenos Aires tango.", "checkpoint": False, "notes": "General"},
    {"turn": 760, "message": "So many dreams.", "checkpoint": False, "notes": "General"},
    {"turn": 761, "message": "Goodnight!", "checkpoint": False, "notes": "General"},
    {"turn": 762, "message": "Oh wait, one more thing — Tom's birthday is in October. Oct 15 specifically.", "checkpoint": False, "notes": "NEW DETAIL: Tom bday Oct 15"},
    {"turn": 763, "message": "That's the cooking class day in Chiang Mai! Perfect birthday activity.", "checkpoint": False, "notes": "Birthday coincidence"},
    {"turn": 764, "message": "We should make it special. Maybe a birthday dinner after.", "checkpoint": False, "notes": "Planning"},
    {"turn": 765, "message": "Budget $100 for Tom's birthday dinner in Chiang Mai.", "checkpoint": False, "notes": "Expense"},
]