"""
1000-Turn Travel Planner Stress Test
======================================
Turns 1-100: Identical to scenario_100.py (Europe trip with Sarah & Tom)
Turns 101-1000: Extended planning across MULTIPLE trips, life changes,
evolving preferences, and increasingly complex memory demands.

NARRATIVE ARC:
- Turns 1-100:   Europe Trip #1 (Paris, Rome, Florence) — Sarah & Tom
- Turns 101-250: Post-trip debrief + Asia Trip (Japan & Thailand)
- Turns 251-400: Disruptions, trip changes, South America trip
- Turns 401-600: Life changes (pregnancy), companion cancellations
- Turns 601-800: More updates, preference evolution
- Turns 801-1000: Final stress — cross-trip recall, contradiction storms

KEY CHANGES TO TRACK:
- Sarah: vegetarian→vegan, stops drinking, becomes pregnant
- Patricia: added→cancelled from Asia trip
- Mike+Lily: added→cancelled from Thailand
- Hotels: multiple switches across trips
- Budgets: Europe $12K, Asia $12.5K, South America $8K
"""

from scenario_100 import SCENARIO as SCENARIO_100

SCENARIO = list(SCENARIO_100) + [

    # === PHASE 11: Post-Europe debrief (Turns 101-120) ===
    {"turn": 101, "message": "Hey! We just got back from Europe. It was amazing!", "checkpoint": False, "notes": "Post-trip"},
    {"turn": 102, "message": "The Hotel Monge in Paris was incredible. But the Campo de' Fiori place in Rome was too noisy.", "checkpoint": False, "notes": "Hotel review"},
    {"turn": 103, "message": "Tom discovered he loves Italian food and wants a pasta-making course next time.", "checkpoint": False, "notes": "Tom preference"},
    {"turn": 104, "message": "I've decided to go fully vegan now, not just vegetarian. The Europe food inspired me.", "checkpoint": False, "notes": "MAJOR: Sarah vegetarian→vegan"},
    {"turn": 105, "message": "What were my dietary restrictions before?", "checkpoint": True,
     "expected": {"must_contain": ["vegetarian"], "must_not_contain": [], "description": "Recall Sarah was vegetarian"}},
    {"turn": 106, "message": "Right, so now I'm vegan. Update that. Tom still has the nut allergy.", "checkpoint": False, "notes": "Confirm vegan"},
    {"turn": 107, "message": "We're thinking about an Asia trip. Japan and Thailand?", "checkpoint": False, "notes": "Trip #2 intro"},
    {"turn": 108, "message": "October, 3 weeks, budget $15,000 for both of us.", "checkpoint": False, "notes": "Asia: Oct, 3wk, $15K"},
    {"turn": 109, "message": "Tom's mom Patricia wants to join for Japan. She's 68 with a bad knee.", "checkpoint": False, "notes": "New companion: Patricia"},
    {"turn": 110, "message": "Patricia is also diabetic and needs to watch sugar intake.", "checkpoint": False, "notes": "Patricia: diabetic"},
    {"turn": 111, "message": "Who's going on the Asia trip and dietary/health needs?", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "vegan", "Tom", "nut", "Patricia", "diabetic|diabetes|sugar", "knee"],
                  "must_not_contain": ["vegetarian", "Emily"], "description": "Asia companions with updated diet"}},
    {"turn": 112, "message": "Japan: week in Tokyo, then Kyoto. Tom wants to see Mount Fuji.", "checkpoint": False, "notes": "Japan plan"},
    {"turn": 113, "message": "Found Sawanoya Ryokan in Tokyo, $180/night, traditional tatami.", "checkpoint": False, "notes": "Tokyo hotel option 1"},
    {"turn": 114, "message": "Wait, Patricia can't sleep on floor futons with her knee.", "checkpoint": False, "notes": "Accessibility issue"},
    {"turn": 115, "message": "Park Hotel Tokyo in Shiodome, $250/night, Western beds, good accessibility. Let's go with that.", "checkpoint": False, "notes": "CHANGE: Sawanoya→Park Hotel"},
    {"turn": 116, "message": "What hotel in Tokyo and why did we change?", "checkpoint": True,
     "expected": {"must_contain": ["Park Hotel"], "must_not_contain": ["Sawanoya"], "description": "Park Hotel, not Sawanoya"}},
    {"turn": 117, "message": "Kyoto: Hyatt Regency, $300/night, 4 nights.", "checkpoint": False, "notes": "Kyoto hotel"},
    {"turn": 118, "message": "After Japan, Patricia flies home. Tom and I continue to Thailand.", "checkpoint": False, "notes": "Patricia Japan only"},
    {"turn": 119, "message": "Thailand: Bangkok 3 days, Chiang Mai 4 days, then Koh Samui beach.", "checkpoint": False, "notes": "Thailand plan"},
    {"turn": 120, "message": "My email changed to sarahj.travels@gmail.com.", "checkpoint": False, "notes": "Email update"},

    # === PHASE 12: Asia logistics (Turns 121-170) ===
    {"turn": 121, "message": "Flights: ANA JFK→NRT Oct 1, $1200/person. Three tickets outbound.", "checkpoint": False, "notes": "Outbound flight"},
    {"turn": 122, "message": "Patricia return: JAL NRT→LAX Oct 10, $900.", "checkpoint": False, "notes": "Patricia return"},
    {"turn": 123, "message": "Tom and I: Thai Airways Tokyo→Bangkok Oct 10, $400 each.", "checkpoint": False, "notes": "Connecting flight"},
    {"turn": 124, "message": "Return: Qatar Airways Bangkok→JFK Oct 22 via Doha, $800 each.", "checkpoint": False, "notes": "Return flight"},
    {"turn": 125, "message": "List all Asia trip flights with costs.", "checkpoint": True,
     "expected": {"must_contain": ["ANA", "1200|1,200", "Japan Airlines|JAL", "900", "Thai Airways", "400", "Qatar", "800"],
                  "must_not_contain": ["American", "United", "Delta"], "description": "All Asia flights"}},
    {"turn": 126, "message": "Tokyo Sushi Academy Oct 3, $95/person, all three.", "checkpoint": False, "notes": "Tokyo activity"},
    {"turn": 127, "message": "Fuji day trip Oct 5, $150 each. Patricia skips (knee), explores Ginza.", "checkpoint": False, "notes": "Fuji — not Patricia"},
    {"turn": 128, "message": "Kyoto tea ceremony Oct 8, $60/person, all three.", "checkpoint": False, "notes": "Kyoto activity"},
    {"turn": 129, "message": "Bangkok hotels: Mandarin Oriental $350/night or Chatrium $120/night?", "checkpoint": False, "notes": "Options"},
    {"turn": 130, "message": "Chatrium Hotel Bangkok, 3 nights.", "checkpoint": False, "notes": "Bangkok hotel"},
    {"turn": 131, "message": "Chiang Mai: Rachamankha Hotel, $160/night, 4 nights. Boutique.", "checkpoint": False, "notes": "CM hotel"},
    {"turn": 132, "message": "Koh Samui: Anantara Bophut, $280/night, 5 nights.", "checkpoint": False, "notes": "KS resort"},
    {"turn": 133, "message": "Total accommodation cost for Asia?", "checkpoint": True,
     "expected": {"must_contain": ["Park Hotel", "Hyatt", "Chatrium", "Rachamankha", "Anantara"],
                  "must_not_contain": ["Sawanoya", "Hotel Monge"], "description": "All Asia hotels"}},
    {"turn": 134, "message": "Mama Noi's Cookery School Chiang Mai Oct 14, $40/person.", "checkpoint": False, "notes": "CM activity"},
    {"turn": 135, "message": "Elephant Nature Park Chiang Mai Oct 15, $80 each.", "checkpoint": False, "notes": "CM activity"},
    {"turn": 136, "message": "Ang Thong Marine Park snorkeling Koh Samui Oct 18, $65/person.", "checkpoint": False, "notes": "KS activity"},
    {"turn": 137, "message": "Tom's been learning Japanese for 3 months!", "checkpoint": False, "notes": "Tom detail"},
    {"turn": 138, "message": "Full Asia itinerary day by day?", "checkpoint": True,
     "expected": {"must_contain": ["October 1", "Tokyo", "Kyoto", "Bangkok", "Chiang Mai", "Koh Samui"],
                  "must_not_contain": ["Paris", "Rome"], "description": "Asia itinerary, no Europe bleed"}},
    {"turn": 139, "message": "Accessible Kyoto temples for Patricia's knee?", "checkpoint": False, "notes": "General"},
    {"turn": 140, "message": "Let's visit Kinkaku-ji Oct 7.", "checkpoint": False, "notes": "Activity"},
    {"turn": 141, "message": "Good vegan restaurants in Bangkok?", "checkpoint": False, "notes": "Vegan ref"},
    {"turn": 142, "message": "Need nut-allergy-safe restaurants in Tokyo for Tom.", "checkpoint": False, "notes": "Allergy ref"},
    {"turn": 143, "message": "Patricia extending 2 days. Flies back Oct 12 instead of Oct 10.", "checkpoint": False, "notes": "CHANGE: Patricia Oct 10→12"},
    {"turn": 144, "message": "New Patricia return: JAL NRT→LAX Oct 12, $950.", "checkpoint": False, "notes": "Flight change"},
    {"turn": 145, "message": "Tom and I still leave Tokyo Oct 10 right?", "checkpoint": True,
     "expected": {"must_contain": ["October 10", "Thai Airways|Bangkok"], "must_not_contain": [], "description": "S+T still Oct 10"}},
    {"turn": 146, "message": "Patricia alone Oct 11-12 in Tokyo. Low-mobility activities?", "checkpoint": False, "notes": "General"},
    {"turn": 147, "message": "Travel insurance: World Nomads $180/person for Tom and me. Patricia has her own.", "checkpoint": False, "notes": "Insurance"},
    {"turn": 148, "message": "Total Asia trip cost so far?", "checkpoint": True,
     "expected": {"must_contain": ["15,000|15000"], "must_not_contain": ["8,000|8000", "12,000|12000"],
                  "description": "Budget is $15000"}},
    {"turn": 149, "message": "Muay Thai class for Tom in Bangkok: Attachai Gym, $30.", "checkpoint": False, "notes": "Activity"},
    {"turn": 150, "message": "Thai massage for me: Let's Relax Spa Bangkok, $50.", "checkpoint": False, "notes": "Activity"},
    {"turn": 151, "message": "Weather in Thailand in October?", "checkpoint": False, "notes": "General"},
    {"turn": 152, "message": "Should we pack rain gear?", "checkpoint": False, "notes": "General"},
    {"turn": 153, "message": "Japan in early October warm?", "checkpoint": False, "notes": "General"},
    {"turn": 154, "message": "Vaccinations for Thailand?", "checkpoint": False, "notes": "General"},
    {"turn": 155, "message": "Visa requirements? We're US citizens.", "checkpoint": False, "notes": "General"},
    {"turn": 156, "message": "Tom wants scuba diving in Koh Samui Oct 19!", "checkpoint": False, "notes": "Activity"},
    {"turn": 157, "message": "PADI discover scuba, $120. Tom never dived before.", "checkpoint": False, "notes": "Scuba detail"},
    {"turn": 158, "message": "I'll do yoga instead. Vikasa Yoga Koh Samui, $75.", "checkpoint": False, "notes": "Sarah activity"},
    {"turn": 159, "message": "All Koh Samui activities?", "checkpoint": True,
     "expected": {"must_contain": ["snorkeling|Ang Thong", "scuba|diving", "yoga|Vikasa"], "must_not_contain": [],
                  "description": "All KS activities"}},
    {"turn": 160, "message": "Total activities cost across the whole trip?", "checkpoint": False, "notes": "Budget Q"},
    {"turn": 161, "message": "Bangkok to Chiang Mai — fly or train?", "checkpoint": False, "notes": "General"},
    {"turn": 162, "message": "Fly. AirAsia BKK→CNX Oct 13, $60 each.", "checkpoint": False, "notes": "Internal flight"},
    {"turn": 163, "message": "Chiang Mai to Koh Samui — fly through Bangkok?", "checkpoint": False, "notes": "General"},
    {"turn": 164, "message": "Bangkok Airways CNX→USM direct Oct 17, $110 each.", "checkpoint": False, "notes": "Internal flight"},
    {"turn": 165, "message": "All Asia flights including internal?", "checkpoint": True,
     "expected": {"must_contain": ["ANA", "Thai Airways", "Qatar", "AirAsia", "Bangkok Airways"],
                  "must_not_contain": ["American", "United", "Delta"], "description": "All Asia flights"}},
    {"turn": 166, "message": "Tom's teacher recommended a ramen tour in Shinjuku.", "checkpoint": False, "notes": "Casual"},
    {"turn": 167, "message": "Tokyo Ramen Tours Shinjuku Oct 4, $70/person. Need vegan + nut-free.", "checkpoint": False, "notes": "Activity w/ dietary"},
    {"turn": 168, "message": "They confirmed vegan + nut-free. Book it!", "checkpoint": False, "notes": "Confirmed"},
    {"turn": 169, "message": "My passport expires January. Need to renew.", "checkpoint": False, "notes": "Personal"},
    {"turn": 170, "message": "Everyone's dietary restrictions and health concerns?", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "vegan", "Tom", "nut", "Patricia", "diabetic|diabetes", "knee"],
                  "must_not_contain": ["vegetarian", "Emily"], "description": "All dietary/health at turn 170"}},

    # === PHASE 13: Budget cut + changes (Turns 171-200) ===
    {"turn": 171, "message": "Bad news — Tom's company cut bonuses. Asia budget drops to $12,000.", "checkpoint": False, "notes": "BUDGET: $15K→$12K"},
    {"turn": 172, "message": "Need cheaper Koh Samui. Anantara at $280/night is too much.", "checkpoint": False, "notes": "Cost cut"},
    {"turn": 173, "message": "Coco Palm Beach Resort Koh Samui, $95/night. Switch to that.", "checkpoint": False, "notes": "CHANGE: Anantara→Coco Palm"},
    {"turn": 174, "message": "Skip scuba diving for Tom. Saves $120.", "checkpoint": False, "notes": "CANCEL: scuba"},
    {"turn": 175, "message": "Updated budget?", "checkpoint": True,
     "expected": {"must_contain": ["12,000|12000"], "must_not_contain": ["15,000|15000", "Anantara"],
                  "description": "Budget $12K, no Anantara"}},
    {"turn": 176, "message": "Patricia worried about the long flight. Might drop out.", "checkpoint": False, "notes": "Patricia uncertain"},
    {"turn": 177, "message": "She'll come but only 5 days: arrive Oct 3, leave Oct 8.", "checkpoint": False, "notes": "CHANGE: Patricia shortened"},
    {"turn": 178, "message": "New Patricia flights: ANA JFK→NRT Oct 3 $1100, JAL NRT→LAX Oct 8 $850.", "checkpoint": False, "notes": "Flight changes"},
    {"turn": 179, "message": "Patricia misses sushi class Oct 3 (arrives that day). Can still do tea ceremony.", "checkpoint": False, "notes": "Impact"},
    {"turn": 180, "message": "Will Patricia be with us in Kyoto?", "checkpoint": True,
     "expected": {"must_contain": ["Kyoto", "Patricia"], "must_not_contain": [], "description": "Kyoto timing vs Patricia"}},
    {"turn": 181, "message": "Rearrange: Kyoto Oct 4-7 so Patricia can join.", "checkpoint": False, "notes": "Rearranged"},
    {"turn": 182, "message": "Tea ceremony → Oct 5 Kyoto. Sushi class stays Oct 3 Tokyo (Tom + me only).", "checkpoint": False, "notes": "Activity dates"},
    {"turn": 183, "message": "Fuji trip → Oct 8 after Patricia leaves.", "checkpoint": False, "notes": "Fuji moved"},
    {"turn": 184, "message": "Shinkansen Tokyo→Kyoto Oct 4, $130/person.", "checkpoint": False, "notes": "Train"},
    {"turn": 185, "message": "Return Kyoto→Tokyo Oct 7, $130 each.", "checkpoint": False, "notes": "Return train"},
    {"turn": 186, "message": "How many Shinkansen tickets? Patricia needs one too?", "checkpoint": True,
     "expected": {"must_contain": ["3|three|Patricia"], "must_not_contain": [], "description": "3 Shinkansen tickets"}},
    {"turn": 187, "message": "Correct, three each way.", "checkpoint": False, "notes": "Confirmed"},
    {"turn": 188, "message": "Restaurant for vegan (me), nut-free (Tom), low-sugar (Patricia) in Kyoto?", "checkpoint": False, "notes": "Dietary test"},
    {"turn": 189, "message": "What about Tokyo?", "checkpoint": False, "notes": "General"},
    {"turn": 190, "message": "Tom wants Akihabara for electronics and manga.", "checkpoint": False, "notes": "Tom interest"},
    {"turn": 191, "message": "October is typhoon season in Japan. Worried?", "checkpoint": False, "notes": "General"},
    {"turn": 192, "message": "Flexible bookings just in case.", "checkpoint": False, "notes": "General"},
    {"turn": 193, "message": "Tom's friend Mike might join us in Thailand. Lives in Singapore.", "checkpoint": False, "notes": "Potential companion"},
    {"turn": 194, "message": "Mike confirmed for Thailand! Meets us Bangkok Oct 10. He's pescatarian.", "checkpoint": False, "notes": "NEW: Mike, pescatarian"},
    {"turn": 195, "message": "Mike gets own hotel, joins activities, pays separately.", "checkpoint": False, "notes": "Mike logistics"},
    {"turn": 196, "message": "Who's on each leg?", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "Tom", "Patricia", "Mike"], "must_not_contain": ["Emily"],
                  "description": "Japan: S+T+Patricia. Thailand: S+T+Mike"}},
    {"turn": 197, "message": "Tom wants to skip Chiang Mai for more Koh Samui.", "checkpoint": False, "notes": "Potential change"},
    {"turn": 198, "message": "Keep Chiang Mai — elephant sanctuary is there.", "checkpoint": False, "notes": "Reverted"},
    {"turn": 199, "message": "Can Mike join elephant sanctuary?", "checkpoint": False, "notes": "Mike activity"},
    {"turn": 200, "message": "Complete Asia trip plan — dates, locations, companions, all bookings.", "checkpoint": True,
     "expected": {"must_contain": ["October", "Tokyo", "Kyoto", "Bangkok", "Chiang Mai", "Koh Samui", "Sarah", "Tom", "Patricia", "Mike", "Park Hotel", "Hyatt", "Chatrium", "Rachamankha", "Coco Palm", "12,000|12000"],
                  "must_not_contain": ["Anantara", "15,000|15000", "Paris", "Sawanoya"],
                  "description": "COMPREHENSIVE ASIA RECALL at turn 200"}},

    # === PHASE 14: Deep details + cross-trip (Turns 201-250) ===
    {"turn": 201, "message": "JR Pass 7-day: $280 each for S+T+Patricia.", "checkpoint": False, "notes": "JR Pass"},
    {"turn": 202, "message": "JR Pass covers Shinkansen — cancel individual tickets.", "checkpoint": False, "notes": "CANCEL Shinkansen tix"},
    {"turn": 203, "message": "Does Patricia need JR Pass too?", "checkpoint": True,
     "expected": {"must_contain": ["Patricia"], "must_not_contain": [], "description": "Patricia JR Pass question"}},
    {"turn": 204, "message": "7-day pass doesn't make sense for 5 days. Individual tickets for Patricia: $260 round trip.", "checkpoint": False, "notes": "Patricia individual"},
    {"turn": 205, "message": "What hotel in Paris on the Europe trip?", "checkpoint": True,
     "expected": {"must_contain": ["Hotel Monge"], "must_not_contain": ["Le Petit Moulin"], "description": "Cross-trip: Europe hotel"}},
    {"turn": 206, "message": "Loved that place. Would stay again.", "checkpoint": False, "notes": "Preference"},
    {"turn": 207, "message": "Ramen tour was Oct 4 but we're in Kyoto Oct 4-7 now. Need to move it.", "checkpoint": False, "notes": "Conflict"},
    {"turn": 208, "message": "Ramen tour → Oct 9 Tokyo.", "checkpoint": False, "notes": "Ramen moved: 4→9"},
    {"turn": 209, "message": "All Tokyo activities with correct dates?", "checkpoint": True,
     "expected": {"must_contain": ["sushi|October 3", "ramen|October 9", "Fuji|October 8"], "must_not_contain": [],
                  "description": "Tokyo activities updated dates"}},
    {"turn": 210, "message": "Mike is allergic to shellfish! Important for Thai food.", "checkpoint": False, "notes": "Mike: shellfish allergy"},
    {"turn": 211, "message": "Packing for Japan autumn + Thai tropical?", "checkpoint": False, "notes": "General"},
    {"turn": 212, "message": "Need outlet adapters for Japan?", "checkpoint": False, "notes": "General"},
    {"turn": 213, "message": "Thailand adapters?", "checkpoint": False, "notes": "General"},
    {"turn": 214, "message": "Pocket wifi Japan: $8/day from Japan Wireless.", "checkpoint": False, "notes": "Detail"},
    {"turn": 215, "message": "How many days for pocket wifi?", "checkpoint": False, "notes": "Calc Q"},
    {"turn": 216, "message": "Gonpachi izakaya Tokyo Oct 2 — inspired Kill Bill!", "checkpoint": False, "notes": "Restaurant"},
    {"turn": 217, "message": "But I'm vegan... can I eat at an izakaya?", "checkpoint": False, "notes": "Vegan test"},
    {"turn": 218, "message": "Good, they have options.", "checkpoint": False, "notes": "General"},
    {"turn": 219, "message": "Travel SIM cards for Thailand?", "checkpoint": False, "notes": "General"},
    {"turn": 220, "message": "Airport to hotel in Tokyo?", "checkpoint": False, "notes": "General"},
    {"turn": 221, "message": "Narita Express — covered by JR Pass?", "checkpoint": False, "notes": "Transport"},
    {"turn": 222, "message": "Patricia arrives Oct 3 separately. Needs Narita to hotel without JR Pass.", "checkpoint": False, "notes": "Patricia transport"},
    {"turn": 223, "message": "Limousine Bus $30 for Patricia.", "checkpoint": False, "notes": "Detail"},
    {"turn": 224, "message": "Currency: Yen + Baht?", "checkpoint": False, "notes": "General"},
    {"turn": 225, "message": "Patricia worried about stairs at Hyatt Kyoto.", "checkpoint": False, "notes": "Accessibility"},
    {"turn": 226, "message": "All health/mobility concerns for this trip?", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "vegan", "Tom", "nut", "Patricia", "knee", "diabetic|diabetes", "Mike", "shellfish"],
                  "must_not_contain": ["vegetarian", "Emily"], "description": "All 4 travelers health at turn 226"}},
    {"turn": 227, "message": "Nara day trip from Kyoto Oct 6. Just Tom and me.", "checkpoint": False, "notes": "Nara trip"},
    {"turn": 228, "message": "Train to Nara cost?", "checkpoint": False, "notes": "General"},
    {"turn": 229, "message": "Covered by JR Pass?", "checkpoint": False, "notes": "General"},
    {"turn": 230, "message": "Day-by-day Japan schedule?", "checkpoint": True,
     "expected": {"must_contain": ["October 1", "Kyoto", "Nara", "Fuji", "ramen"], "must_not_contain": [],
                  "description": "Japan day-by-day"}},
    {"turn": 231, "message": "Tom's teacher said try tonkotsu ramen.", "checkpoint": False, "notes": "Detail"},
    {"turn": 232, "message": "Hope there's vegan ramen too.", "checkpoint": False, "notes": "Vegan ref"},
    {"turn": 233, "message": "Buy Kinkaku-ji tickets in advance?", "checkpoint": False, "notes": "General"},
    {"turn": 234, "message": "What about the Colosseum — wait, that's Europe! Getting trips mixed up!", "checkpoint": False, "notes": "Cross-trip confusion"},
    {"turn": 235, "message": "What activities on the Europe trip?", "checkpoint": True,
     "expected": {"must_contain": ["Colosseum", "Seine|cruise", "Uffizi|Florence"],
                  "must_not_contain": ["sushi", "ramen", "elephant"], "description": "Europe activities only"}},
    {"turn": 236, "message": "Back to Asia. Total cost with all changes?", "checkpoint": False, "notes": "Budget"},
    {"turn": 237, "message": "Might need to cut more.", "checkpoint": False, "notes": "General"},
    {"turn": 238, "message": "Cancel yoga retreat Koh Samui. Saves $75.", "checkpoint": False, "notes": "CANCEL: yoga"},
    {"turn": 239, "message": "Skip Nara day trip too.", "checkpoint": False, "notes": "CANCEL: Nara"},
    {"turn": 240, "message": "What activities still on schedule?", "checkpoint": True,
     "expected": {"must_contain": ["sushi", "tea ceremony", "Fuji", "ramen", "cooking|Mama Noi", "elephant", "snorkeling|Ang Thong"],
                  "must_not_contain": ["yoga|Vikasa", "Nara", "scuba"], "description": "Remaining activities"}},
    {"turn": 241, "message": "Packing list essentials?", "checkpoint": False, "notes": "General"},
    {"turn": 242, "message": "Lightweight carry-on recommendations?", "checkpoint": False, "notes": "General"},
    {"turn": 243, "message": "Tom into craft beer. Bangkok craft beer bars?", "checkpoint": False, "notes": "Tom pref"},
    {"turn": 244, "message": "Chiang Mai night markets?", "checkpoint": False, "notes": "General"},
    {"turn": 245, "message": "Sunday Night Market. What day do we arrive CM?", "checkpoint": False, "notes": "Schedule Q"},
    {"turn": 246, "message": "Oct 13 is Tuesday. Miss Sunday market.", "checkpoint": False, "notes": "Date calc"},
    {"turn": 247, "message": "Other first evening options in CM?", "checkpoint": False, "notes": "General"},
    {"turn": 248, "message": "Gyms near Chatrium Bangkok? Tom likes to work out.", "checkpoint": False, "notes": "General"},
    {"turn": 249, "message": "Hotel pool decent? I swim mornings.", "checkpoint": False, "notes": "General"},
    {"turn": 250, "message": "Full status check: Asia plan, budget, who's involved.", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "vegan", "Tom", "nut", "Patricia", "Mike", "shellfish", "12,000|12000", "Tokyo", "Kyoto", "Bangkok", "Chiang Mai", "Koh Samui"],
                  "must_not_contain": ["15,000|15000", "vegetarian", "Anantara", "scuba", "yoga|Vikasa", "Nara"],
                  "description": "COMPREHENSIVE at turn 250"}},

    # === PHASE 15: Major reschedule (Turns 251-300) ===
    {"turn": 251, "message": "Tom has work conference Oct 1-3. Must push departure.", "checkpoint": False, "notes": "MAJOR delay"},
    {"turn": 252, "message": "Fly out Oct 4 instead. Lose 3 Tokyo days.", "checkpoint": False, "notes": "New departure"},
    {"turn": 253, "message": "Cancel sushi class Oct 3. Need new outbound flights.", "checkpoint": False, "notes": "CANCEL: sushi"},
    {"turn": 254, "message": "ANA JFK→NRT Oct 4, $1100/person. Two tickets (Patricia arrives separately Oct 3).", "checkpoint": False, "notes": "New outbound"},
    {"turn": 255, "message": "Patricia alone Tokyo Oct 3-4 until we arrive evening Oct 4?", "checkpoint": True,
     "expected": {"must_contain": ["Patricia", "October 3", "October 4"], "must_not_contain": [],
                  "description": "Patricia arrives before S+T"}},
    {"turn": 256, "message": "She's fine. Will rest at Park Hotel Tokyo.", "checkpoint": False, "notes": "Correct hotel ref"},
    {"turn": 257, "message": "Rearranging Japan. First full day Oct 5.", "checkpoint": False, "notes": "Restructure"},
    {"turn": 258, "message": "Oct 5-6 Tokyo with Patricia, Oct 7-9 Kyoto (all three), Oct 10 back, Patricia home Oct 10, Bangkok Oct 11.", "checkpoint": False, "notes": "New schedule"},
    {"turn": 259, "message": "Tea ceremony → Oct 8 Kyoto. Fuji — when?", "checkpoint": False, "notes": "Activity scheduling"},
    {"turn": 260, "message": "Skip Fuji. Too rushed with shortened schedule.", "checkpoint": False, "notes": "CANCEL: Fuji"},
    {"turn": 261, "message": "Ramen tour → Oct 10, last day in Japan.", "checkpoint": False, "notes": "Ramen moved: 9→10"},
    {"turn": 262, "message": "Revised Japan itinerary?", "checkpoint": True,
     "expected": {"must_contain": ["October 5", "Kyoto", "October 10", "ramen"],
                  "must_not_contain": ["Fuji", "October 1", "sushi class|sushi-making"], "description": "Revised Japan no Fuji/sushi"}},
    {"turn": 263, "message": "Thailand dates shift. Leave Tokyo Oct 11, arrive Bangkok Oct 11.", "checkpoint": False, "notes": "Thailand shift"},
    {"turn": 264, "message": "Mike now Oct 11 instead of 10.", "checkpoint": False, "notes": "Mike date change"},
    {"turn": 265, "message": "Thailand: Bangkok Oct 11-13, Chiang Mai Oct 14-17, Koh Samui Oct 18-22, home Oct 23.", "checkpoint": False, "notes": "Updated Thailand"},
    {"turn": 266, "message": "Rebook internals: AirAsia Oct 14, Bangkok Airways Oct 18.", "checkpoint": False, "notes": "Shifted flights"},
    {"turn": 267, "message": "Return: Qatar BKK→JFK Oct 23, $850 each.", "checkpoint": False, "notes": "Return changed"},
    {"turn": 268, "message": "Mama Noi's → Oct 15.", "checkpoint": False, "notes": "Activity shift"},
    {"turn": 269, "message": "Elephant sanctuary → Oct 16.", "checkpoint": False, "notes": "Activity shift"},
    {"turn": 270, "message": "Snorkeling → Oct 19.", "checkpoint": False, "notes": "Activity shift"},
    {"turn": 271, "message": "Complete updated timeline.", "checkpoint": True,
     "expected": {"must_contain": ["October 4", "October 5", "October 11", "October 23", "Kyoto", "Bangkok", "Chiang Mai", "Koh Samui"],
                  "must_not_contain": ["October 1", "October 22", "Fuji"], "description": "Full updated timeline"}},
    {"turn": 272, "message": "Mike wants seafood in Bangkok. He loves seafood.", "checkpoint": False, "notes": "But shellfish allergy!"},
    {"turn": 273, "message": "Right, shellfish allergy. Fish only. Good catch.", "checkpoint": False, "notes": "Agent flagged it"},
    {"turn": 274, "message": "Chao Phraya dinner cruise Oct 12, $55/person, all of us in Bangkok.", "checkpoint": False, "notes": "Bangkok activity"},
    {"turn": 275, "message": "How many on that cruise?", "checkpoint": True,
     "expected": {"must_contain": ["3|three|Sarah|Tom|Mike"], "must_not_contain": ["Patricia"],
                  "description": "Cruise: S+T+Mike"}},
    {"turn": 276, "message": "Three people. Patricia Japan only.", "checkpoint": False, "notes": "Confirmed"},
    {"turn": 277, "message": "Thailand weather forecast?", "checkpoint": False, "notes": "General"},
    {"turn": 278, "message": "Bring umbrellas or buy there?", "checkpoint": False, "notes": "General"},
    {"turn": 279, "message": "Tom's company reimbursing $500. Budget help!", "checkpoint": False, "notes": "Budget boost"},
    {"turn": 280, "message": "Effective budget now $12,500.", "checkpoint": False, "notes": "BUDGET: $12K→$12.5K"},
    {"turn": 281, "message": "Power adapter for Thailand?", "checkpoint": False, "notes": "General"},
    {"turn": 282, "message": "Mike bringing one to share.", "checkpoint": False, "notes": "General"},
    {"turn": 283, "message": "Bangkok Food Tours Oct 11, $35/person, three of us.", "checkpoint": False, "notes": "Activity"},
    {"turn": 284, "message": "Needs to accommodate vegan, nut allergy, shellfish allergy!", "checkpoint": False, "notes": "3 dietary needs"},
    {"turn": 285, "message": "Confirmed all accommodated. Book it!", "checkpoint": False, "notes": "Confirmed"},
    {"turn": 286, "message": "Tom has flight anxiety now. JFK→Tokyo flight time?", "checkpoint": False, "notes": "Tom health"},
    {"turn": 287, "message": "14 hours. He might get medication.", "checkpoint": False, "notes": "General"},
    {"turn": 288, "message": "Current accommodation list for whole Asia trip?", "checkpoint": True,
     "expected": {"must_contain": ["Park Hotel Tokyo", "Hyatt", "Chatrium", "Rachamankha", "Coco Palm"],
                  "must_not_contain": ["Hotel Monge", "Anantara", "Sawanoya"], "description": "All Asia hotels"}},
    {"turn": 289, "message": "Chatrium breakfast vegan options?", "checkpoint": False, "notes": "General"},
    {"turn": 290, "message": "Rachamankha breakfast?", "checkpoint": False, "notes": "General"},
    {"turn": 291, "message": "Thai language apps for Tom?", "checkpoint": False, "notes": "General"},
    {"turn": 292, "message": "Already learning Japanese AND Thai? Ambitious!", "checkpoint": False, "notes": "Tom ref"},
    {"turn": 293, "message": "Total nights away?", "checkpoint": False, "notes": "Calc"},
    {"turn": 294, "message": "Need time off Oct 3-24 with jet lag buffer.", "checkpoint": False, "notes": "Personal"},
    {"turn": 295, "message": "Tom working remote from Bangkok.", "checkpoint": False, "notes": "Detail"},
    {"turn": 296, "message": "Travel docs needed?", "checkpoint": False, "notes": "General"},
    {"turn": 297, "message": "Passport renewed, expires 2036.", "checkpoint": False, "notes": "Updated"},
    {"turn": 298, "message": "Total spending vs budget?", "checkpoint": True,
     "expected": {"must_contain": ["12,500|12500"], "must_not_contain": ["15,000|15000", "8,000|8000"],
                  "description": "Budget is $12,500"}},
    {"turn": 299, "message": "Pretty good! Haven't accounted for food and shopping.", "checkpoint": False, "notes": "General"},
    {"turn": 300, "message": "MEGA CHECKPOINT: Everything about BOTH trips — Europe AND Asia. Every person, dietary restriction, hotel, key activity, budget.", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "vegan", "Tom", "nut", "Patricia", "diabetic|diabetes", "knee", "Mike", "shellfish", "Hotel Monge", "Park Hotel Tokyo", "Hyatt", "Chatrium", "Rachamankha", "Coco Palm", "12,500|12500"],
                  "must_not_contain": ["vegetarian", "Emily", "Anantara", "Sawanoya", "15,000|15000", "8,000|8000"],
                  "description": "MEGA CHECKPOINT at turn 300"}},

    # === PHASE 16: South America Trip + changes (Turns 301-400) ===
    {"turn": 301, "message": "Exciting news: planning South America for March! Peru and Argentina.", "checkpoint": False, "notes": "Trip #3"},
    {"turn": 302, "message": "10 days, budget $10,000. Just Tom and me.", "checkpoint": False, "notes": "SA basics"},
    {"turn": 303, "message": "No companions this time.", "checkpoint": False, "notes": "Just S+T"},
    {"turn": 304, "message": "Must do Machu Picchu!", "checkpoint": False, "notes": "Key activity"},
    {"turn": 305, "message": "Argentina: Buenos Aires, maybe Patagonia.", "checkpoint": False, "notes": "Destinations"},
    {"turn": 306, "message": "Tom's nut allergy — extra careful in SA. Lots of nuts in dishes.", "checkpoint": False, "notes": "Dietary concern"},
    {"turn": 307, "message": "How many trips planned now?", "checkpoint": True,
     "expected": {"must_contain": ["Europe", "Asia|Japan|Thailand", "South America|Peru|Argentina"], "must_not_contain": [],
                  "description": "Three trips"}},
    {"turn": 308, "message": "SA dates: March 5-15.", "checkpoint": False, "notes": "Dates"},
    {"turn": 309, "message": "Peru: Lima 2 days, Cusco/Machu Picchu 3 days.", "checkpoint": False, "notes": "Peru plan"},
    {"turn": 310, "message": "Argentina: 5 days Buenos Aires.", "checkpoint": False, "notes": "BA plan"},
    {"turn": 311, "message": "Lima: Belmond Miraflores Park, $200/night.", "checkpoint": False, "notes": "Lima hotel"},
    {"turn": 312, "message": "Cusco: Palacio del Inka, $180/night.", "checkpoint": False, "notes": "Cusco hotel"},
    {"turn": 313, "message": "Buenos Aires: Alvear Palace, $250/night.", "checkpoint": False, "notes": "BA hotel"},
    {"turn": 314, "message": "Inca Trail trek: 2-day with Alpaca Expeditions, $350/person.", "checkpoint": False, "notes": "Trek booking"},
    {"turn": 315, "message": "Rojo Tango dinner show BA, $120/person.", "checkpoint": False, "notes": "BA activity"},
    {"turn": 316, "message": "Don Julio steakhouse — but I'm vegan. Tom can enjoy steak.", "checkpoint": False, "notes": "Vegan ref"},
    {"turn": 317, "message": "SA trip so far?", "checkpoint": True,
     "expected": {"must_contain": ["March", "Lima", "Cusco|Machu Picchu", "Buenos Aires", "10,000|10000", "Belmond", "Palacio", "Alvear"],
                  "must_not_contain": ["Tokyo", "Bangkok", "Paris"], "description": "SA details only"}},
    {"turn": 318, "message": "Back to Asia — Mike asking snorkeling cost?", "checkpoint": False, "notes": "Cross-trip"},
    {"turn": 319, "message": "$65/person at Ang Thong.", "checkpoint": False, "notes": "Confirms"},
    {"turn": 320, "message": "Tom wants Mendoza vineyard. Need domestic flight.", "checkpoint": False, "notes": "Potential addition"},
    {"turn": 321, "message": "Mendoza too far for 10 days. Wine tasting in BA instead.", "checkpoint": False, "notes": "Mendoza skipped"},
    {"turn": 322, "message": "Anuva Wines in Palermo BA, $80/person.", "checkpoint": False, "notes": "Wine tasting"},
    {"turn": 323, "message": "Wait — I don't drink anymore! Stopped after Europe trip.", "checkpoint": False, "notes": "MAJOR: Sarah no alcohol"},
    {"turn": 324, "message": "Wine tasting just Tom. $80 for one.", "checkpoint": False, "notes": "Tom only"},
    {"turn": 325, "message": "What do I eat and drink now?", "checkpoint": True,
     "expected": {"must_contain": ["vegan", "no alcohol|doesn't drink|stopped drinking|don't drink"],
                  "must_not_contain": ["vegetarian"], "description": "Sarah: vegan + no alcohol"}},
    {"turn": 326, "message": "Altitude sickness meds for Cusco?", "checkpoint": False, "notes": "Health"},
    {"turn": 327, "message": "Tom's nut allergy affected by altitude?", "checkpoint": False, "notes": "General"},
    {"turn": 328, "message": "Vaccinations for Peru?", "checkpoint": False, "notes": "General"},
    {"turn": 329, "message": "Yellow fever. Will schedule.", "checkpoint": False, "notes": "General"},
    {"turn": 330, "message": "Safety in Lima/BA?", "checkpoint": False, "notes": "General"},
    {"turn": 331, "message": "Patricia's flight schedule for Asia?", "checkpoint": True,
     "expected": {"must_contain": ["Patricia", "October 3", "October 8|October 10"], "must_not_contain": [],
                  "description": "Patricia current dates"}},
    {"turn": 332, "message": "Patricia NOT on South America right?", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "Tom"], "must_not_contain": ["Patricia", "Mike"],
                  "description": "SA: just Sarah+Tom"}},
    {"turn": 333, "message": "Just us two.", "checkpoint": False, "notes": "Confirmed"},
    {"turn": 334, "message": "Flights: LATAM JFK→Lima March 5, $650/person.", "checkpoint": False, "notes": "SA outbound"},
    {"turn": 335, "message": "Lima→Cusco March 7, LATAM domestic, $120 each.", "checkpoint": False, "notes": "Internal"},
    {"turn": 336, "message": "Cusco→Buenos Aires March 10, Aerolineas Argentinas, $250 each.", "checkpoint": False, "notes": "Internal"},
    {"turn": 337, "message": "BA→JFK March 15, American Airlines, $700 each.", "checkpoint": False, "notes": "Return"},
    {"turn": 338, "message": "All SA flights.", "checkpoint": True,
     "expected": {"must_contain": ["LATAM", "Aerolineas", "American"],
                  "must_not_contain": ["ANA", "Thai Airways", "Qatar", "Delta", "United"], "description": "SA flights only"}},
    {"turn": 339, "message": "Good vegan restaurant Lima?", "checkpoint": False, "notes": "Vegan ref"},
    {"turn": 340, "message": "Vegan options in BA? Argentina is beef country.", "checkpoint": False, "notes": "Vegan ref"},
    {"turn": 341, "message": "Tom eating steak for both of us haha.", "checkpoint": False, "notes": "Chatter"},
    {"turn": 342, "message": "Best time for Machu Picchu?", "checkpoint": False, "notes": "General"},
    {"turn": 343, "message": "Early morning. Trek starts day before.", "checkpoint": False, "notes": "General"},
    {"turn": 344, "message": "Complete SA itinerary with all bookings.", "checkpoint": True,
     "expected": {"must_contain": ["March 5", "Lima", "Cusco", "Machu Picchu|Inca Trail", "Buenos Aires", "March 15", "Belmond", "Palacio", "Alvear", "tango", "Alpaca"],
                  "must_not_contain": ["Tokyo", "Paris", "Bangkok"], "description": "Complete SA"}},
    {"turn": 345, "message": "Travel insurance for SA? Same World Nomads?", "checkpoint": False, "notes": "Insurance"},
    {"turn": 346, "message": "World Nomads $150/person for SA.", "checkpoint": False, "notes": "Insurance booking"},
    {"turn": 347, "message": "SA budget vs spending?", "checkpoint": True,
     "expected": {"must_contain": ["10,000|10000"], "must_not_contain": ["12,000|12000|12,500|12500"],
                  "description": "SA budget $10K"}},
    {"turn": 348, "message": "Under budget? Want food/souvenir money.", "checkpoint": False, "notes": "General"},
    {"turn": 349, "message": "Keep $1500 buffer for food.", "checkpoint": False, "notes": "Budget note"},
    {"turn": 350, "message": "All trips, dates, budgets?", "checkpoint": True,
     "expected": {"must_contain": ["Europe", "June", "Asia|Japan", "October", "South America|Peru", "March", "12,500|12500", "10,000|10000"],
                  "must_not_contain": ["15,000|15000", "8,000|8000"], "description": "Three trips summary"}},

    # === PHASE 17: Patricia cancels, more changes (Turns 351-400) ===
    {"turn": 351, "message": "Patricia might cancel Japan entirely. Doctor concerned about long flight.", "checkpoint": False, "notes": "Patricia uncertain"},
    {"turn": 352, "message": "She cancelled. Doctor said no to long flights with her knee.", "checkpoint": False, "notes": "PATRICIA CANCELLED"},
    {"turn": 353, "message": "Who's going to Asia now?", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "Tom", "Mike"], "must_not_contain": ["Patricia"],
                  "description": "Asia: S+T (Japan) + Mike (Thailand)"}},
    {"turn": 354, "message": "Without Patricia, don't need accessible hotel. Switch back to ryokan?", "checkpoint": False, "notes": "Reconsidering"},
    {"turn": 355, "message": "Back to Sawanoya Ryokan, $180/night!", "checkpoint": False, "notes": "CHANGE: Park Hotel→Sawanoya"},
    {"turn": 356, "message": "What hotel in Tokyo now?", "checkpoint": True,
     "expected": {"must_contain": ["Sawanoya"], "must_not_contain": ["Park Hotel"], "description": "Sawanoya, not Park"}},
    {"turn": 357, "message": "Keep Hyatt Kyoto. Still great.", "checkpoint": False, "notes": "Keeping Hyatt"},
    {"turn": 358, "message": "How much were Patricia's flights?", "checkpoint": False, "notes": "Budget recalc"},
    {"turn": 359, "message": "Cancel tea ceremony for 3→2. Cancel Patricia's Shinkansen tickets.", "checkpoint": False, "notes": "Multiple cancels"},
    {"turn": 360, "message": "Revised Asia budget without Patricia?", "checkpoint": True,
     "expected": {"must_contain": ["12,500|12500"], "must_not_contain": ["Patricia", "15,000|15000"],
                  "description": "Budget $12.5K, no Patricia"}},
    {"turn": 361, "message": "Tom wants to send Patricia a silk kimono from Japan.", "checkpoint": False, "notes": "Gift"},
    {"turn": 362, "message": "Where to buy kimono in Tokyo?", "checkpoint": False, "notes": "General"},
    {"turn": 363, "message": "Budget $200 for kimono gift.", "checkpoint": False, "notes": "Expense"},
    {"turn": 364, "message": "Mike bringing girlfriend Lily to Koh Samui only, Oct 18-22.", "checkpoint": False, "notes": "NEW: Lily"},
    {"turn": 365, "message": "Lily is lactose intolerant.", "checkpoint": False, "notes": "Lily: lactose"},
    {"turn": 366, "message": "Who's on each leg of Asia now?", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "Tom", "Mike", "Lily"], "must_not_contain": ["Patricia", "Emily"],
                  "description": "Japan:S+T. Thailand:S+T+Mike. KS:+Lily"}},
    {"turn": 367, "message": "So many changes!", "checkpoint": False, "notes": "General"},
    {"turn": 368, "message": "Japan: Tom+me. Thailand mainland: +Mike. Koh Samui: +Lily. Correct?", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "Tom", "Mike", "Lily"], "must_not_contain": ["Patricia"],
                  "description": "Companion breakdown by leg"}},
    {"turn": 369, "message": "Glad we're keeping track.", "checkpoint": False, "notes": "General"},
    {"turn": 370, "message": "Europe trip budget? Just curious.", "checkpoint": True,
     "expected": {"must_contain": ["12,000|12000"], "must_not_contain": ["8,000|8000", "10,000|10000"],
                  "description": "Europe budget was $12K"}},
    {"turn": 371, "message": "Total all trips: $34,500. Wow!", "checkpoint": False, "notes": "Math"},
    {"turn": 372, "message": "Let's reduce SA budget to $8,000.", "checkpoint": False, "notes": "BUDGET: SA $10K→$8K"},
    {"turn": 373, "message": "Need cheaper BA hotel. Alvear $250/night too much.", "checkpoint": False, "notes": "Cost cut"},
    {"turn": 374, "message": "Mine Hotel BA, boutique, $120/night.", "checkpoint": False, "notes": "CHANGE: Alvear→Mine Hotel"},
    {"turn": 375, "message": "SA hotels now?", "checkpoint": True,
     "expected": {"must_contain": ["Belmond", "Palacio", "Mine Hotel"], "must_not_contain": ["Alvear"],
                  "description": "Updated SA hotels"}},
    {"turn": 376, "message": "SA budget is $8,000 now?", "checkpoint": True,
     "expected": {"must_contain": ["8,000|8000"], "must_not_contain": ["10,000|10000"], "description": "SA=$8K"}},
    {"turn": 377, "message": "Packing for Machu Picchu?", "checkpoint": False, "notes": "General"},
    {"turn": 378, "message": "Layers for altitude?", "checkpoint": False, "notes": "General"},
    {"turn": 379, "message": "Tom buying new hiking boots.", "checkpoint": False, "notes": "General"},
    {"turn": 380, "message": "Need to train for the trek.", "checkpoint": False, "notes": "General"},
    {"turn": 381, "message": "Machu Picchu elevation?", "checkpoint": False, "notes": "General"},
    {"turn": 382, "message": "Cusco elevation?", "checkpoint": False, "notes": "General"},
    {"turn": 383, "message": "Arrive Cusco day early to acclimatize.", "checkpoint": False, "notes": "General"},
    {"turn": 384, "message": "Inca Trail food: vegan + nut-free?", "checkpoint": False, "notes": "Dietary concern"},
    {"turn": 385, "message": "Will email Alpaca Expeditions.", "checkpoint": False, "notes": "General"},
    {"turn": 386, "message": "Good steak + vegan restaurants in BA?", "checkpoint": False, "notes": "General"},
    {"turn": 387, "message": "Don Julio has vegan dishes. Going there.", "checkpoint": False, "notes": "General"},
    {"turn": 388, "message": "Argentine peso exchange rate?", "checkpoint": False, "notes": "General"},
    {"turn": 389, "message": "Peruvian soles?", "checkpoint": False, "notes": "General"},
    {"turn": 390, "message": "Cash or cards in Peru/Argentina?", "checkpoint": False, "notes": "General"},
    {"turn": 391, "message": "How much was Inca Trail per person?", "checkpoint": False, "notes": "Price recall"},
    {"turn": 392, "message": "$350. How many people?", "checkpoint": True,
     "expected": {"must_contain": ["2|two|Sarah|Tom"], "must_not_contain": ["Patricia", "Mike", "Lily"],
                  "description": "Inca Trail: just S+T"}},
    {"turn": 393, "message": "What tango show in BA?", "checkpoint": False, "notes": "Recall test"},
    {"turn": 394, "message": "Rojo Tango! Exciting.", "checkpoint": False, "notes": "Confirms"},
    {"turn": 395, "message": "BA street art tour, La Boca, $25/person.", "checkpoint": False, "notes": "Activity"},
    {"turn": 396, "message": "Lima food tour, $45/person. Needs vegan options.", "checkpoint": False, "notes": "Activity"},
    {"turn": 397, "message": "They confirmed vegan. Book it!", "checkpoint": False, "notes": "Confirmed"},
    {"turn": 398, "message": "Love all this traveling!", "checkpoint": False, "notes": "Chatter"},
    {"turn": 399, "message": "Any loose ends on SA trip?", "checkpoint": False, "notes": "General"},
    {"turn": 400, "message": "BIG CHECKPOINT: All three trips — dates, budgets, companions, dietary restrictions, health concerns.", "checkpoint": True,
     "expected": {"must_contain": ["Europe", "June", "Asia|Japan|Thailand", "October", "South America|Peru|Argentina", "March",
                                    "Sarah", "vegan", "Tom", "nut", "Mike", "shellfish|pescatarian", "Lily", "lactose",
                                    "12,500|12500", "8,000|8000"],
                  "must_not_contain": ["Patricia", "Emily", "vegetarian", "15,000|15000", "10,000|10000"],
                  "description": "GRAND CHECKPOINT turn 400"}},
]

# Print summary
if __name__ == "__main__":
    total = len(SCENARIO)
    checkpoints = [s for s in SCENARIO if s["checkpoint"]]
    print(f"Travel Planner Stress Test ({total}-turn, PART 1)")
    print(f"  Total turns: {total}")
    print(f"  Checkpoints: {len(checkpoints)}")