"""
scenario_1000_final.py — Turns 766-1000 continuation
This file should be concatenated into scenario_1000.py
"""

SCENARIO_FINAL = [
    {"turn": 766, "message": "Patricia: knee. Mike: work. Lily: followed Mike.", "checkpoint": False, "notes": "Summary"},
    {"turn": 767, "message": "Life is unpredictable.", "checkpoint": False, "notes": "General"},
    {"turn": 768, "message": "At least Sarah and Tom are constant!", "checkpoint": False, "notes": "General"},
    {"turn": 769, "message": "What was my original dietary restriction when we started planning?", "checkpoint": True,
     "expected": {"must_contain": ["vegetarian"], "must_not_contain": [], "description": "Original: vegetarian"}},
    {"turn": 770, "message": "And now?", "checkpoint": True,
     "expected": {"must_contain": ["vegan"], "must_not_contain": ["vegetarian"], "description": "Current: vegan"}},
    {"turn": 771, "message": "Plus no alcohol and pregnant. What a journey.", "checkpoint": False, "notes": "General"},
    {"turn": 772, "message": "How many companions came and went across all our planning?", "checkpoint": False, "notes": "Meta Q"},
    {"turn": 773, "message": "Emily (Europe, removed), Patricia (Asia, cancelled), Mike (Thailand, cancelled), Lily (KS, cancelled). Four people!", "checkpoint": False, "notes": "History"},
    {"turn": 774, "message": "And the original Europe trip budget?", "checkpoint": True,
     "expected": {"must_contain": ["8,000|8000|12,000|12000"], "must_not_contain": [],
                  "description": "Europe started at $8K, went to $12K"}},
    {"turn": 775, "message": "It changed from $8000 to $12000 during planning right?", "checkpoint": False, "notes": "General"},
    {"turn": 776, "message": "Correct.", "checkpoint": False, "notes": "General"},
    {"turn": 777, "message": "Asia went from $15K to $12K to $12.5K. Lots of changes.", "checkpoint": False, "notes": "History"},
    {"turn": 778, "message": "SA from $10K to $8K.", "checkpoint": False, "notes": "History"},
    {"turn": 779, "message": "We're good at adapting!", "checkpoint": False, "notes": "General"},
    {"turn": 780, "message": "Tom says we should make a shared Google Doc with all the trip details.", "checkpoint": False, "notes": "General"},
    {"turn": 781, "message": "Good idea. Can you help me organize it?", "checkpoint": False, "notes": "General"},
    {"turn": 782, "message": "Let me test your memory one more time. Europe trip cities?", "checkpoint": True,
     "expected": {"must_contain": ["Paris", "Rome", "Florence"], "must_not_contain": ["Barcelona"],
                  "description": "Europe cities (Barcelona was dropped)"}},
    {"turn": 783, "message": "Asia cities?", "checkpoint": True,
     "expected": {"must_contain": ["Tokyo", "Kyoto", "Bangkok", "Chiang Mai", "Koh Samui"],
                  "must_not_contain": ["Osaka"], "description": "Asia cities"}},
    {"turn": 784, "message": "South America cities?", "checkpoint": True,
     "expected": {"must_contain": ["Lima", "Cusco", "Buenos Aires"],
                  "must_not_contain": ["Mendoza", "Patagonia"], "description": "SA cities (no Mendoza)"}},
    {"turn": 785, "message": "Perfect!", "checkpoint": False, "notes": "General"},
    {"turn": 786, "message": "What's the total number of cities across all trips?", "checkpoint": False, "notes": "Count Q"},
    {"turn": 787, "message": "11 cities! That's impressive.", "checkpoint": False, "notes": "General"},
    {"turn": 788, "message": "We'll have SO many stories to tell.", "checkpoint": False, "notes": "General"},
    {"turn": 789, "message": "And photos. Tom's new camera will get a workout.", "checkpoint": False, "notes": "General"},
    {"turn": 790, "message": "I want to make a photo book for each trip.", "checkpoint": False, "notes": "General"},
    {"turn": 791, "message": "And a special one for the baby to see someday.", "checkpoint": False, "notes": "General"},
    {"turn": 792, "message": "The before-baby adventures!", "checkpoint": False, "notes": "General"},
    {"turn": 793, "message": "Tom's already planning baby's first international trip. He's thinking Costa Rica.", "checkpoint": False, "notes": "General"},
    {"turn": 794, "message": "That's a planning problem for next year!", "checkpoint": False, "notes": "General"},
    {"turn": 795, "message": "Let's focus on getting through these three trips first.", "checkpoint": False, "notes": "General"},
    {"turn": 796, "message": "When's the first trip?", "checkpoint": True,
     "expected": {"must_contain": ["October", "Asia|Japan"], "must_not_contain": [],
                  "description": "Next trip: Asia in October"}},
    {"turn": 797, "message": "About a month away!", "checkpoint": False, "notes": "General"},
    {"turn": 798, "message": "Then SA in March.", "checkpoint": False, "notes": "General"},
    {"turn": 799, "message": "We're going to have an amazing year.", "checkpoint": False, "notes": "General"},
    {"turn": 800, "message": "CHECKPOINT 800: Complete state of all trips including every hotel, major activity, companion, budget, dietary restriction.", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "vegan", "pregnant", "Tom", "nut",
                                    "Europe", "Hotel Monge", "12,000|12000",
                                    "Asia", "October", "Sawanoya", "Hyatt", "Chatrium", "Rachamankha", "Coco Palm", "12,500|12500",
                                    "South America", "March", "Belmond", "Palacio", "Mine Hotel", "8,000|8000",
                                    "ramen", "tea ceremony", "elephant", "tango", "PeruRail|train"],
                  "must_not_contain": ["Patricia", "Mike", "Lily", "Emily", "vegetarian", "Park Hotel", "Anantara", "Alvear",
                                       "Fuji", "Inca Trail|trek", "15,000|15000", "10,000|10000", "scuba", "yoga", "sushi class"],
                  "description": "CHECKPOINT 800: Everything current"}},

    # === PHASE 23: Final stress — Turns 801-1000 ===
    # Heavy recall, contradiction tests, cross-trip memory
    {"turn": 801, "message": "I had a dream we were still going to Barcelona. We dropped that city early on right?", "checkpoint": True,
     "expected": {"must_contain": ["Barcelona"], "must_not_contain": [], "description": "Barcelona dropped from Europe"}},
    {"turn": 802, "message": "What replaced it?", "checkpoint": True,
     "expected": {"must_contain": ["Florence"], "must_not_contain": [], "description": "Florence replaced Barcelona"}},
    {"turn": 803, "message": "Right! The Uffizi was amazing.", "checkpoint": False, "notes": "General"},
    {"turn": 804, "message": "What hotel did we stay at in Rome?", "checkpoint": True,
     "expected": {"must_contain": ["Campo de' Fiori"], "must_not_contain": ["Le Petit Moulin"],
                  "description": "Rome hotel from Europe trip"}},
    {"turn": 805, "message": "The noisy one! Not booking that again.", "checkpoint": False, "notes": "Preference"},
    {"turn": 806, "message": "Tom learned from that — now he always checks noise reviews.", "checkpoint": False, "notes": "General"},
    {"turn": 807, "message": "What was the best hotel on our Europe trip?", "checkpoint": True,
     "expected": {"must_contain": ["Hotel Monge"], "must_not_contain": [], "description": "Best Europe hotel: Monge"}},
    {"turn": 808, "message": "Definitely. OK rapid fire dietary quiz:", "checkpoint": False, "notes": "Quiz intro"},
    {"turn": 809, "message": "What can I NOT eat? List everything.", "checkpoint": True,
     "expected": {"must_contain": ["vegan", "no alcohol|doesn't drink|don't drink"],
                  "must_not_contain": ["vegetarian"], "description": "Sarah restrictions: vegan + no alcohol"}},
    {"turn": 810, "message": "What must Tom avoid?", "checkpoint": True,
     "expected": {"must_contain": ["nut|peanut|tree nut"], "must_not_contain": [], "description": "Tom: nuts"}},
    {"turn": 811, "message": "Any other health concerns for either of us?", "checkpoint": True,
     "expected": {"must_contain": ["pregnant|pregnancy", "flight anxiety|anxiety"],
                  "must_not_contain": [], "description": "Sarah pregnant, Tom flight anxiety"}},
    {"turn": 812, "message": "Right. Pregnant me and anxious flyer Tom. What a pair!", "checkpoint": False, "notes": "General"},
    {"turn": 813, "message": "But we're brave travelers.", "checkpoint": False, "notes": "General"},
    {"turn": 814, "message": "What was my email before I changed it?", "checkpoint": False, "notes": "Hard recall test"},
    {"turn": 815, "message": "And my current email?", "checkpoint": True,
     "expected": {"must_contain": ["sarahj.travels@gmail.com"], "must_not_contain": [],
                  "description": "Current email"}},
    {"turn": 816, "message": "How many times did the Tokyo hotel change?", "checkpoint": False, "notes": "Meta Q"},
    {"turn": 817, "message": "Sawanoya → Park Hotel (for Patricia) → Sawanoya (Patricia cancelled). Twice!", "checkpoint": False, "notes": "General"},
    {"turn": 818, "message": "And the Koh Samui hotel?", "checkpoint": False, "notes": "Meta Q"},
    {"turn": 819, "message": "Anantara → Coco Palm (budget cut). Once.", "checkpoint": False, "notes": "General"},
    {"turn": 820, "message": "And Buenos Aires?", "checkpoint": False, "notes": "Meta Q"},
    {"turn": 821, "message": "Alvear → Mine Hotel (budget cut). Once.", "checkpoint": False, "notes": "General"},
    {"turn": 822, "message": "You have a great memory for all these changes.", "checkpoint": False, "notes": "General"},
    {"turn": 823, "message": "How was the original Asia trip budget different from now?", "checkpoint": True,
     "expected": {"must_contain": ["15,000|15000", "12,500|12500"], "must_not_contain": [],
                  "description": "Asia budget went from $15K to $12.5K"}},
    {"turn": 824, "message": "And the SA budget change?", "checkpoint": True,
     "expected": {"must_contain": ["10,000|10000", "8,000|8000"], "must_not_contain": [],
                  "description": "SA budget went from $10K to $8K"}},

    # Turns 825-900: Extended filler and checkpoints
    {"turn": 825, "message": "Tom's counting down the days. 25 to go!", "checkpoint": False, "notes": "General"},
    {"turn": 826, "message": "Me too. The nesting instinct is real but travel excitement wins.", "checkpoint": False, "notes": "General"},
    {"turn": 827, "message": "Should we buy JR Pass online or at the airport?", "checkpoint": False, "notes": "General"},
    {"turn": 828, "message": "Online is cheaper. Let's order now.", "checkpoint": False, "notes": "General"},
    {"turn": 829, "message": "For how many people?", "checkpoint": True,
     "expected": {"must_contain": ["2|two"], "must_not_contain": ["3|three"],
                  "description": "JR Pass for 2 (Patricia cancelled)"}},
    {"turn": 830, "message": "Right, just us two. No Patricia, no JR Pass for her.", "checkpoint": False, "notes": "Confirmed"},
    {"turn": 831, "message": "What about the Shinkansen — are we using the JR Pass for that now?", "checkpoint": True,
     "expected": {"must_contain": ["JR Pass|yes|covered"], "must_not_contain": [],
                  "description": "JR Pass covers Shinkansen"}},
    {"turn": 832, "message": "Perfect. Saving money there.", "checkpoint": False, "notes": "General"},
    {"turn": 833, "message": "How many nights at the Sawanoya?", "checkpoint": False, "notes": "Calc Q"},
    {"turn": 834, "message": "We're in Tokyo Oct 4 evening through Oct 7 morning, then again Oct 9-11. So about 5 nights.", "checkpoint": False, "notes": "General"},
    {"turn": 835, "message": "And Hyatt Kyoto?", "checkpoint": False, "notes": "Calc Q"},
    {"turn": 836, "message": "Oct 7-9. About 2-3 nights.", "checkpoint": False, "notes": "General"},
    {"turn": 837, "message": "Everything is falling into place.", "checkpoint": False, "notes": "General"},
    {"turn": 838, "message": "Tom's Japanese teacher gave him a list of Tokyo restaurants. He's so prepared.", "checkpoint": False, "notes": "General"},
    {"turn": 839, "message": "I love how into this he is.", "checkpoint": False, "notes": "General"},
    {"turn": 840, "message": "What's the last thing we booked for the Asia trip?", "checkpoint": False, "notes": "Meta Q"},
    {"turn": 841, "message": "I think it was the spa in Koh Samui.", "checkpoint": False, "notes": "General"},
    {"turn": 842, "message": "Tamarind Springs, Oct 20. Babymoon vibes.", "checkpoint": False, "notes": "Activity ref"},
    {"turn": 843, "message": "And for SA, last booking?", "checkpoint": False, "notes": "Meta Q"},
    {"turn": 844, "message": "The PeruRail train replacing the Inca Trail.", "checkpoint": False, "notes": "Activity ref"},
    {"turn": 845, "message": "Smart change given pregnancy.", "checkpoint": False, "notes": "General"},
    {"turn": 846, "message": "Doctor said Cusco altitude is fine for 20 weeks but take it very easy.", "checkpoint": False, "notes": "Medical"},
    {"turn": 847, "message": "We'll rest a lot.", "checkpoint": False, "notes": "General"},
    {"turn": 848, "message": "Tom will carry all the bags.", "checkpoint": False, "notes": "General"},
    {"turn": 849, "message": "He's a good husband.", "checkpoint": False, "notes": "General"},
    {"turn": 850, "message": "And going to be a great dad!", "checkpoint": False, "notes": "General"},
    {"turn": 851, "message": "Quick quiz: name all the cooking/food classes we've booked across all trips.", "checkpoint": True,
     "expected": {"must_contain": ["Mama Noi|cooking class", "ramen|Tokyo Ramen", "food tour|Lima|Bangkok"],
                  "must_not_contain": ["Roma Cooking Academy|sushi class"],
                  "description": "Current food experiences (not cancelled ones)"}},
    {"turn": 852, "message": "Good memory!", "checkpoint": False, "notes": "General"},
    {"turn": 853, "message": "I keep wanting to add more activities but we should leave room for spontaneity.", "checkpoint": False, "notes": "General"},
    {"turn": 854, "message": "Tom agrees. Some of the best travel moments are unplanned.", "checkpoint": False, "notes": "General"},
    {"turn": 855, "message": "Like finding that amazing gelato place in Rome.", "checkpoint": False, "notes": "Europe ref"},
    {"turn": 856, "message": "I couldn't eat dairy even then — wait, was I already vegan during Europe?", "checkpoint": True,
     "expected": {"must_contain": ["vegetarian|no"], "must_not_contain": [],
                  "description": "Sarah was vegetarian during Europe, went vegan after"}},
    {"turn": 857, "message": "Right! I was still vegetarian then. Went vegan after we got back.", "checkpoint": False, "notes": "Confirmed timeline"},
    {"turn": 858, "message": "What's the first city we visit on the Asia trip?", "checkpoint": True,
     "expected": {"must_contain": ["Tokyo"], "must_not_contain": ["Kyoto"], "description": "Tokyo first"}},
    {"turn": 859, "message": "And last city?", "checkpoint": True,
     "expected": {"must_contain": ["Koh Samui"], "must_not_contain": ["Bangkok"], "description": "Koh Samui last"}},
    {"turn": 860, "message": "First city in SA?", "checkpoint": True,
     "expected": {"must_contain": ["Lima"], "must_not_contain": [], "description": "Lima first in SA"}},
    {"turn": 861, "message": "Last?", "checkpoint": True,
     "expected": {"must_contain": ["Buenos Aires"], "must_not_contain": [], "description": "BA last in SA"}},
    {"turn": 862, "message": "We always end on a high note!", "checkpoint": False, "notes": "General"},
    {"turn": 863, "message": "I'm going to write a blog about our travels.", "checkpoint": False, "notes": "General"},
    {"turn": 864, "message": "Vegan pregnant traveler — catchy title.", "checkpoint": False, "notes": "General"},
    {"turn": 865, "message": "Tom can be the photographer and I'll be the writer.", "checkpoint": False, "notes": "General"},
    {"turn": 866, "message": "We make a good team.", "checkpoint": False, "notes": "General"},
    {"turn": 867, "message": "Speaking of teams — do you remember everyone who was EVER planned to be on any of our trips?", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "Tom", "Emily", "Patricia", "Mike", "Lily"],
                  "must_not_contain": [],
                  "description": "All companions ever: Sarah, Tom, Emily, Patricia, Mike, Lily"}},
    {"turn": 868, "message": "Six people total across all planning. But in the end, just us two.", "checkpoint": False, "notes": "General"},
    {"turn": 869, "message": "Simpler. More romantic.", "checkpoint": False, "notes": "General"},
    {"turn": 870, "message": "And cheaper!", "checkpoint": False, "notes": "General"},

    # Final approach to 1000
    {"turn": 871, "message": "Any last-minute changes to make?", "checkpoint": False, "notes": "General"},
    {"turn": 872, "message": "I think we're good. Everything is booked.", "checkpoint": False, "notes": "General"},
    {"turn": 873, "message": "Tom agrees. No more changes!", "checkpoint": False, "notes": "General"},
    {"turn": 874, "message": "Famous last words haha.", "checkpoint": False, "notes": "General"},
    {"turn": 875, "message": "What's our accommodation preference been consistently?", "checkpoint": True,
     "expected": {"must_contain": ["boutique"], "must_not_contain": [], "description": "Consistent preference: boutique"}},
    {"turn": 876, "message": "Boutique hotels all the way!", "checkpoint": False, "notes": "General"},
    {"turn": 877, "message": "Even the Sawanoya is boutique-ish. It's a family-run ryokan.", "checkpoint": False, "notes": "General"},
    {"turn": 878, "message": "I need a pre-trip spa day here at home.", "checkpoint": False, "notes": "General"},
    {"turn": 879, "message": "Tom's getting a haircut before the trip. Wants to look good in photos.", "checkpoint": False, "notes": "General"},
    {"turn": 880, "message": "Vanity haha.", "checkpoint": False, "notes": "General"},
    {"turn": 881, "message": "What's the longest flight on any of our trips?", "checkpoint": False, "notes": "General"},
    {"turn": 882, "message": "JFK to Tokyo is about 14 hours. That's the longest.", "checkpoint": False, "notes": "General"},
    {"turn": 883, "message": "Tom's anxiety is going to be tested.", "checkpoint": False, "notes": "General"},
    {"turn": 884, "message": "He'll be fine. He has meds now.", "checkpoint": False, "notes": "General"},
    {"turn": 885, "message": "And me next to him.", "checkpoint": False, "notes": "General"},
    {"turn": 886, "message": "We've been through a LOT of planning together.", "checkpoint": False, "notes": "General"},
    {"turn": 887, "message": "From that first message about Europe to now — three trips, multiple companions, budget changes, life changes.", "checkpoint": False, "notes": "General"},
    {"turn": 888, "message": "It's been a journey!", "checkpoint": False, "notes": "General"},
    {"turn": 889, "message": "What was the very first thing I told you when we started planning?", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "Europe|trip", "summer"], "must_not_contain": [],
                  "description": "Very first message: Sarah planning Europe summer trip"}},
    {"turn": 890, "message": "That feels like forever ago.", "checkpoint": False, "notes": "General"},

    {"turn": 891, "message": "How many times did our Asia trip departure date change?", "checkpoint": False, "notes": "Meta Q"},
    {"turn": 892, "message": "Originally Oct 1, then Oct 4 (Tom's conference). Once.", "checkpoint": False, "notes": "General"},
    {"turn": 893, "message": "What activities did we cancel across ALL trips? List them all.", "checkpoint": True,
     "expected": {"must_contain": ["sushi class|sushi-making", "scuba", "yoga|Vikasa", "Nara", "Fuji", "Inca Trail|trek"],
                  "must_not_contain": [],
                  "description": "All cancelled activities across all trips"}},
    {"turn": 894, "message": "Lots of cancellations! But the remaining ones are great.", "checkpoint": False, "notes": "General"},
    {"turn": 895, "message": "Quality over quantity.", "checkpoint": False, "notes": "General"},
    {"turn": 896, "message": "Tom's counting: 20 days until Asia trip!", "checkpoint": False, "notes": "General"},
    {"turn": 897, "message": "So exciting!", "checkpoint": False, "notes": "General"},
    {"turn": 898, "message": "I can't sleep I'm so excited.", "checkpoint": False, "notes": "General"},
    {"turn": 899, "message": "Tom's the same. He's up late watching Japan travel vlogs.", "checkpoint": False, "notes": "General"},

    {"turn": 900, "message": "CHECKPOINT 900: All companions who were EVER planned, what happened to each, and who's actually going now.", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "Tom", "Emily", "Patricia", "Mike", "Lily"],
                  "must_not_contain": [],
                  "description": "CHECKPOINT 900: Complete companion history"}},

    # Final 100 turns — mix of chatter and the ultimate final checkpoint
    {"turn": 901, "message": "We should create a WhatsApp group for trip coordination.", "checkpoint": False, "notes": "General"},
    {"turn": 902, "message": "Just us two though haha. Small group.", "checkpoint": False, "notes": "General"},
    {"turn": 903, "message": "Tom's packing list: camera, epi-pen, anxiety meds, hiking shoes, laptop for remote work.", "checkpoint": False, "notes": "Tom packing"},
    {"turn": 904, "message": "My packing list: prenatal vitamins, compression socks, comfortable shoes, maternity clothes.", "checkpoint": False, "notes": "Sarah packing"},
    {"turn": 905, "message": "We're ready!", "checkpoint": False, "notes": "General"},
    {"turn": 906, "message": "One more thing — we should exchange some yen before we go.", "checkpoint": False, "notes": "General"},
    {"turn": 907, "message": "And get baht at the airport in Bangkok.", "checkpoint": False, "notes": "General"},
    {"turn": 908, "message": "For SA trip, soles and pesos.", "checkpoint": False, "notes": "General"},
    {"turn": 909, "message": "So many currencies!", "checkpoint": False, "notes": "General"},
    {"turn": 910, "message": "How many different currencies do we need across all trips?", "checkpoint": False, "notes": "Count Q"},
    {"turn": 911, "message": "Euro, Yen, Baht, Soles, Pesos. Five currencies.", "checkpoint": False, "notes": "Count"},
    {"turn": 912, "message": "International travel is wild.", "checkpoint": False, "notes": "General"},
    {"turn": 913, "message": "Tom downloaded a currency converter app.", "checkpoint": False, "notes": "General"},
    {"turn": 914, "message": "Smart.", "checkpoint": False, "notes": "General"},
    {"turn": 915, "message": "What language is Tom learning?", "checkpoint": True,
     "expected": {"must_contain": ["Japanese"], "must_not_contain": [], "description": "Tom learning Japanese"}},
    {"turn": 916, "message": "He was also learning some Thai.", "checkpoint": False, "notes": "General"},
    {"turn": 917, "message": "Polyglot in the making.", "checkpoint": False, "notes": "General"},
    {"turn": 918, "message": "I should learn some too. At least basic greetings.", "checkpoint": False, "notes": "General"},
    {"turn": 919, "message": "Konnichiwa!", "checkpoint": False, "notes": "General"},
    {"turn": 920, "message": "Tom's mom Patricia sends another message. She wants us to visit a specific temple in Kyoto for good luck with the baby.", "checkpoint": False, "notes": "Patricia ref"},
    {"turn": 921, "message": "That's so sweet! We'll definitely do that.", "checkpoint": False, "notes": "General"},
    {"turn": 922, "message": "What temple does she recommend?", "checkpoint": False, "notes": "General"},
    {"turn": 923, "message": "She said Suzumushi-dera. Known for wish-granting.", "checkpoint": False, "notes": "General"},
    {"turn": 924, "message": "We'll add it to our Kyoto list.", "checkpoint": False, "notes": "General"},
    {"turn": 925, "message": "How many days in Kyoto?", "checkpoint": True,
     "expected": {"must_contain": ["3|three|October 7|October 9"], "must_not_contain": [],
                  "description": "Kyoto ~3 days"}},
    {"turn": 926, "message": "Plenty of time for temples.", "checkpoint": False, "notes": "General"},
    {"turn": 927, "message": "And the tea ceremony.", "checkpoint": False, "notes": "Activity ref"},
    {"turn": 928, "message": "What date is the tea ceremony?", "checkpoint": True,
     "expected": {"must_contain": ["October 8"], "must_not_contain": [], "description": "Tea ceremony Oct 8"}},
    {"turn": 929, "message": "I'm going to wear a kimono for it.", "checkpoint": False, "notes": "General"},
    {"turn": 930, "message": "Tom too? A yukata maybe.", "checkpoint": False, "notes": "General"},
    {"turn": 931, "message": "That would be amazing.", "checkpoint": False, "notes": "General"},
    {"turn": 932, "message": "Alright, I think we've covered everything.", "checkpoint": False, "notes": "General"},
    {"turn": 933, "message": "Have we though? With our track record of changes...", "checkpoint": False, "notes": "Humor"},
    {"turn": 934, "message": "No more changes! We promised!", "checkpoint": False, "notes": "General"},
    {"turn": 935, "message": "Tom swears on his steak dinner at Don Julio.", "checkpoint": False, "notes": "General"},
    {"turn": 936, "message": "Haha deal.", "checkpoint": False, "notes": "General"},
    {"turn": 937, "message": "What's the spa in Koh Samui again?", "checkpoint": True,
     "expected": {"must_contain": ["Tamarind"], "must_not_contain": [], "description": "Tamarind Springs quick recall"}},
    {"turn": 938, "message": "And the date?", "checkpoint": True,
     "expected": {"must_contain": ["October 20"], "must_not_contain": [], "description": "Spa Oct 20"}},
    {"turn": 939, "message": "Can't wait!", "checkpoint": False, "notes": "General"},
    {"turn": 940, "message": "Prenatal massage on a tropical island. Dreams.", "checkpoint": False, "notes": "General"},
    {"turn": 941, "message": "Tom's going to love surfing.", "checkpoint": False, "notes": "General"},
    {"turn": 942, "message": "When does he surf?", "checkpoint": True,
     "expected": {"must_contain": ["October 21"], "must_not_contain": [], "description": "Surf Oct 21"}},
    {"turn": 943, "message": "While I nap on the beach.", "checkpoint": False, "notes": "General"},
    {"turn": 944, "message": "Perfect division of activities.", "checkpoint": False, "notes": "General"},
    {"turn": 945, "message": "I had a thought — should we buy any gifts for Tom's work colleagues who covered for him?", "checkpoint": False, "notes": "General"},
    {"turn": 946, "message": "Good idea. Japanese snacks or Thai silk.", "checkpoint": False, "notes": "General"},
    {"turn": 947, "message": "Budget another $100 for colleague gifts.", "checkpoint": False, "notes": "Expense"},
    {"turn": 948, "message": "And Peruvian alpaca wool for Patricia.", "checkpoint": False, "notes": "General"},
    {"turn": 949, "message": "Plus the kimono from Japan. $200 for that.", "checkpoint": False, "notes": "Gift ref"},
    {"turn": 950, "message": "She'll love it.", "checkpoint": False, "notes": "General"},

    {"turn": 951, "message": "CHECKPOINT 951: What cancelled activities from the Inca Trail were replaced by what?", "checkpoint": True,
     "expected": {"must_contain": ["Inca Trail|trek|Alpaca", "train|PeruRail"],
                  "must_not_contain": [], "description": "Inca Trail→PeruRail train"}},

    {"turn": 952, "message": "Smart swap.", "checkpoint": False, "notes": "General"},
    {"turn": 953, "message": "I wonder what the baby will think of all our travel stories.", "checkpoint": False, "notes": "General"},
    {"turn": 954, "message": "Born with wanderlust!", "checkpoint": False, "notes": "General"},
    {"turn": 955, "message": "Tom's already bought a onesie that says 'Future Traveler'.", "checkpoint": False, "notes": "General"},
    {"turn": 956, "message": "Adorable.", "checkpoint": False, "notes": "General"},
    {"turn": 957, "message": "OK last stretch of planning chat.", "checkpoint": False, "notes": "General"},
    {"turn": 958, "message": "Any final confirmations needed?", "checkpoint": False, "notes": "General"},
    {"turn": 959, "message": "All flights booked?", "checkpoint": True,
     "expected": {"must_contain": ["ANA", "Thai Airways", "AirAsia", "Bangkok Airways", "Qatar", "LATAM", "Aerolineas", "American"],
                  "must_not_contain": ["Delta", "United"], "description": "All airlines across both upcoming trips"}},
    {"turn": 960, "message": "All hotels?", "checkpoint": True,
     "expected": {"must_contain": ["Sawanoya", "Hyatt", "Chatrium", "Rachamankha", "Coco Palm", "Belmond", "Palacio", "Mine Hotel"],
                  "must_not_contain": ["Park Hotel", "Anantara", "Alvear"],
                  "description": "All current hotels"}},
    {"turn": 961, "message": "All major activities?", "checkpoint": True,
     "expected": {"must_contain": ["ramen", "tea ceremony", "elephant", "cooking|Mama Noi", "snorkeling", "tango", "street art", "PeruRail|train|Machu Picchu"],
                  "must_not_contain": ["Fuji", "Inca Trail|trek", "scuba", "yoga", "sushi class"],
                  "description": "All current activities (not cancelled ones)"}},
    {"turn": 962, "message": "Budget for each trip?", "checkpoint": True,
     "expected": {"must_contain": ["12,500|12500", "8,000|8000"],
                  "must_not_contain": ["15,000|15000", "10,000|10000"],
                  "description": "Asia $12.5K, SA $8K"}},
    {"turn": 963, "message": "Dietary needs?", "checkpoint": True,
     "expected": {"must_contain": ["vegan", "nut"], "must_not_contain": ["vegetarian", "shellfish", "lactose"],
                  "description": "Current: vegan (Sarah) + nut (Tom). No Mike/Lily restrictions."}},
    {"turn": 964, "message": "Health concerns?", "checkpoint": True,
     "expected": {"must_contain": ["pregnant|pregnancy", "nut|allergy|epi"],
                  "must_not_contain": ["knee", "diabetic"],
                  "description": "Current health: pregnancy + nut allergy. No Patricia concerns."}},
    {"turn": 965, "message": "Everything checks out!", "checkpoint": False, "notes": "General"},
    {"turn": 966, "message": "We're the most organized travelers ever.", "checkpoint": False, "notes": "General"},
    {"turn": 967, "message": "Thanks to you keeping track of everything.", "checkpoint": False, "notes": "General"},
    {"turn": 968, "message": "It's been fun! Complicated, but fun.", "checkpoint": False, "notes": "General"},
    {"turn": 969, "message": "The most complicated part was all the companion changes.", "checkpoint": False, "notes": "General"},
    {"turn": 970, "message": "Emily, Patricia, Mike, Lily — all came and went.", "checkpoint": False, "notes": "General"},
    {"turn": 971, "message": "And budget changes. Multiple per trip.", "checkpoint": False, "notes": "General"},
    {"turn": 972, "message": "And my dietary evolution: vegetarian to vegan.", "checkpoint": False, "notes": "General"},
    {"turn": 973, "message": "And stopping drinking.", "checkpoint": False, "notes": "General"},
    {"turn": 974, "message": "And becoming pregnant!", "checkpoint": False, "notes": "General"},
    {"turn": 975, "message": "A LOT has changed.", "checkpoint": False, "notes": "General"},
    {"turn": 976, "message": "But the core plan is solid.", "checkpoint": False, "notes": "General"},
    {"turn": 977, "message": "Tom and Sarah conquering the world!", "checkpoint": False, "notes": "General"},
    {"turn": 978, "message": "Before the baby conquers us!", "checkpoint": False, "notes": "Humor"},
    {"turn": 979, "message": "Haha!", "checkpoint": False, "notes": "General"},
    {"turn": 980, "message": "I think I'm going to cry when we land in Tokyo.", "checkpoint": False, "notes": "General"},
    {"turn": 981, "message": "Happy tears.", "checkpoint": False, "notes": "General"},
    {"turn": 982, "message": "Tom will probably cry too. He's a softie.", "checkpoint": False, "notes": "General"},
    {"turn": 983, "message": "We're going to have the time of our lives.", "checkpoint": False, "notes": "General"},
    {"turn": 984, "message": "Thank you for being such an amazing travel planning assistant.", "checkpoint": False, "notes": "General"},
    {"turn": 985, "message": "It's been a long journey of planning!", "checkpoint": False, "notes": "General"},
    {"turn": 986, "message": "From turn 1 to turn 986!", "checkpoint": False, "notes": "Meta"},
    {"turn": 987, "message": "My name is?", "checkpoint": True,
     "expected": {"must_contain": ["Sarah"], "must_not_contain": [], "description": "Name recall: Sarah"}},
    {"turn": 988, "message": "And my husband?", "checkpoint": True,
     "expected": {"must_contain": ["Tom"], "must_not_contain": [], "description": "Husband: Tom"}},
    {"turn": 989, "message": "Due date for baby?", "checkpoint": True,
     "expected": {"must_contain": ["August"], "must_not_contain": [], "description": "Baby due August"}},
    {"turn": 990, "message": "How many trips are we taking?", "checkpoint": True,
     "expected": {"must_contain": ["3|three"], "must_not_contain": [], "description": "Three trips"}},

    # ===================================================================
    # TURN 991-1000: THE ULTIMATE FINAL CHECKPOINT
    # ===================================================================
    {"turn": 991, "message": "OK. I want to test you one final time.", "checkpoint": False, "notes": "Setup"},
    {"turn": 992, "message": "This is the big one.", "checkpoint": False, "notes": "Setup"},
    {"turn": 993, "message": "Give me my complete traveler profile.", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "vegan", "pregnant", "August", "no alcohol|doesn't drink|don't drink", "sarahj.travels@gmail.com", "boutique"],
                  "must_not_contain": ["vegetarian"],
                  "description": "FINAL: Complete Sarah profile"}},
    {"turn": 994, "message": "Tom's complete profile.", "checkpoint": True,
     "expected": {"must_contain": ["Tom", "nut|peanut", "Japanese", "flight anxiety|anxiety", "craft beer"],
                  "must_not_contain": [],
                  "description": "FINAL: Complete Tom profile"}},
    {"turn": 995, "message": "All hotels across both upcoming trips, in order.", "checkpoint": True,
     "expected": {"must_contain": ["Sawanoya", "Hyatt", "Chatrium", "Rachamankha", "Coco Palm", "Belmond", "Palacio", "Mine Hotel"],
                  "must_not_contain": ["Park Hotel", "Anantara", "Alvear", "Sawanoya Ryokan"],
                  "description": "FINAL: All 8 hotels in order"}},
    {"turn": 996, "message": "All airlines across both trips.", "checkpoint": True,
     "expected": {"must_contain": ["ANA", "Thai Airways", "AirAsia", "Bangkok Airways", "Qatar", "LATAM", "Aerolineas", "American"],
                  "must_not_contain": ["Delta", "United", "Japan Airlines|JAL"],
                  "description": "FINAL: All airlines (no cancelled ones)"}},
    {"turn": 997, "message": "Both budgets.", "checkpoint": True,
     "expected": {"must_contain": ["12,500|12500", "8,000|8000"],
                  "must_not_contain": ["15,000|15000", "10,000|10000"],
                  "description": "FINAL: Asia $12.5K, SA $8K"}},
    {"turn": 998, "message": "Every person who was EVER involved in any trip, and their final status.", "checkpoint": True,
     "expected": {"must_contain": ["Sarah", "Tom", "Emily", "Patricia", "Mike", "Lily"],
                  "must_not_contain": [],
                  "description": "FINAL: All 6 people ever involved"}},

    {"turn": 999, "message": (
        "ULTIMATE FINAL CHECKPOINT: Give me EVERYTHING. "
        "All three trips with dates, cities, hotels, flights, activities, budgets. "
        "Both travelers' complete profiles — dietary, health, preferences. "
        "Every cancelled item. Every budget change. Everything."
    ), "checkpoint": True,
     "expected": {
         "must_contain": [
             "Sarah", "vegan", "pregnant", "Tom", "nut",
             "Europe", "June", "Paris", "Rome", "Florence", "Hotel Monge", "12,000|12000",
             "Asia", "October", "Tokyo", "Kyoto", "Bangkok", "Chiang Mai", "Koh Samui",
             "Sawanoya", "Hyatt", "Chatrium", "Rachamankha", "Coco Palm",
             "ANA", "Qatar", "12,500|12500",
             "South America", "March", "Lima", "Cusco", "Buenos Aires",
             "Belmond", "Palacio", "Mine Hotel",
             "LATAM", "American", "8,000|8000",
             "ramen", "tea ceremony", "elephant", "tango", "PeruRail|train"
         ],
         "must_not_contain": [
             "vegetarian", "Park Hotel", "Anantara", "Alvear",
             "Fuji", "Inca Trail|trek", "scuba", "yoga",
             "15,000|15000", "10,000|10000",
             "sushi class"
         ],
         "description": "THE ULTIMATE FINAL CHECKPOINT — EVERYTHING AT TURN 999"
     }},

    {"turn": 1000, "message": "Thank you for everything. Here's to the adventures ahead!", "checkpoint": False,
     "notes": "End of 1000-turn scenario"},
]

# Print summary
if __name__ == "__main__":
    total = len(SCENARIO)
    checkpoints = [s for s in SCENARIO if s["checkpoint"]]
    print(f"  Total turns: {total}")
    print(f"  Checkpoints: {len(checkpoints)}")